module.exports = [
  {
    slug: 'leiden',
    name: 'Leiden',
    region: 'Zuid-Holland en Utrecht',
    nearby: ['hoofddorp', 'den-haag', 'haarlem', 'aalsmeer', 'rotterdam'],
    photo: { src: 'rolstoelbus-voorkant-baksteen.jpg', alt: 'Rolstoelbus voor een gebouw van rode baksteen', pos: 'center 55%' },
    metaDescription: 'Rolstoeltaxi Leiden: rolstoelvervoer naar de binnenstad, de universiteit en de zorg, vanuit Amsterdam en de Haarlemmermeer. Laadklep, 24/7 spoedservice. Bel direct.',
    lead: 'Leiden is een universiteitsstad met grachten, bruggen en veel historie. Voor een rolstoelrit betekent dat: een prachtige omgeving, maar niet overal even toegankelijk.',
    intro: [
      'De Leidse binnenstad kent veel bruggen, smalle straten en fietsers. Voor een grote bus is de binnenstad niet altijd bereikbaar, en voor iemand in een rolstoel zijn kasseien en trottoirbanden lastig. Wij spreken vooraf af waar u wordt opgehaald, zodat de laadklep veilig kan worden uitgeklapt.',
      'Leiden ligt tussen de Randstad en de kust. Veel ritten gaan naar Den Haag, Hoofddorp en Amsterdam, maar ook naar de bollenstreek en de kust. Wij plannen zowel een enkele rit als een vast schema.',
    ],
    plekken: [
      { t: 'Station Leiden Centraal', d: 'Een groot knooppunt. Wij regelen het laatste stuk vanaf het station naar uw bestemming.' },
      { t: 'Hortus botanicus en Rapenburg', d: 'De oudste botanische tuin van Nederland en de bekendste gracht van de stad.' },
      { t: 'Burcht van Leiden', d: 'Een historisch monument in het centrum. We zetten u zo dicht mogelijk af.' },
      { t: 'Pieterskerk en het Pieterskerkhof', d: 'Een van de bekendste plekken in de binnenstad.' },
      { t: 'Naturalis', d: 'Het natuurhistorisch museum, goed bereikbaar. We regelen heen en terug.' },
      { t: 'Bio Science Park', d: 'Het universiteits- en onderzoeksterrein. Voor werk en studie plannen we een vast schema.' },
    ],
    ritten: [
      { t: 'Leiden naar Den Haag', d: 'Naar het zuiden, voor afspraken of familiebezoek.' },
      { t: 'Leiden naar Schiphol', d: 'Voor vluchten, met bagage en ruim de tijd.' },
      { t: 'Leiden naar Amsterdam', d: 'Een dagje stad of een afspraak.' },
      { t: 'Leiden naar de bollenstreek', d: 'Voor een dagje naar de bloemenvelden in het seizoen.' },
      { t: 'Binnen Leiden', d: 'Van huis naar dagbesteding, de huisarts of een afspraak.' },
    ],
    spoed: 'In Leiden kan spoed nodig zijn bij een ontslag of onverwachte afspraak. Bel de spoedlijn met uw adres en bestemming, dan noemen we de aankomsttijd en de prijs.',
    bereik: 'Het Leidse centrum heeft veel bruggen en smalle straten. Onze chauffeurs kiezen de juiste route en spreken vooraf een ophaalpunt af. Buiten het centrum is de bus doorgaans tot voor de deur.',
    faqs: [
      { q: 'Kan de bus in de Leidse binnenstad komen?', a: 'Vaak tot vlak bij de bestemming. In smalle straten spreken we vooraf een ophaalpunt af.' },
      { q: 'Rijden jullie ook naar de kust?', a: 'Ja, naar Katwijk, Noordwijk en de rest van de Rijnstreek.' },
      { q: 'Kan ik een vaste rit afspreken?', a: 'Ja, bijvoorbeeld voor werk, studie of dagbesteding.' },
      { q: 'Kunnen jullie \'s nachts rijden?', a: 'Ja, we zijn 24/7 bereikbaar.' },
    ],
  },

  {
    slug: 'den-haag',
    name: 'Den Haag',
    region: 'Zuid-Holland en Utrecht',
    nearby: ['leiden', 'rotterdam', 'amsterdam', 'schiphol', 'utrecht'],
    photo: { src: 'rolstoelbus-zorginstelling.jpg', alt: 'Rolstoelbus geparkeerd bij een zorgcentrum', pos: 'center' },
    metaDescription: 'Rolstoeltaxi Den Haag: rolstoelvervoer naar het centrum, Scheveningen en de zorg, vanuit Amsterdam en de regio. Elektrische laadklep, 24/7 spoedservice. Bel direct.',
    lead: 'Den Haag is de stad van het Binnenhof, het Vredespaleis en Scheveningen. Voor een rolstoelrit betekent dat: veel bezoekers, veel afspraken en veel overheid.',
    intro: [
      'Den Haag is de zetel van de regering en van internationale hoven. Dat trekt bezoekers, en dat maakt de binnenstad druk. Voor een rolstoelrit betekent het: vooraf plannen, een goede afzetplek kiezen en rekening houden met beveiligde zones.',
      'Daarnaast is er Scheveningen aan de kust, het strand, de pier en het Kurhaus. Wij rijden u er naartoe en terug, en helpen op drukke dagen bij het vinden van een geschikte plek.',
    ],
    plekken: [
      { t: 'Binnenhof en Plein', d: 'Het politieke hart van Nederland. Rond het Binnenhof gelden beperkingen, dus we spreken vooraf een afzetplek af.' },
      { t: 'Vredespaleis', d: 'Een van de bekendste gebouwen van de stad, goed bereikbaar.' },
      { t: 'Scheveningen en de pier', d: 'Strand, boulevard en het Kurhaus. Voor een dagje aan zee halen we u op.' },
      { t: 'Madurodam', d: 'Een uitje voor gezinnen. We regelen heen en terug.' },
      { t: 'Den Haag Centraal en Hollands Spoor', d: 'De twee grote stations. Wij regelen het laatste stuk als het openbaar vervoer niet lukt.' },
      { t: 'Mauritshuis', d: 'Het museum naast het Binnenhof. We zetten u af zo dicht mogelijk bij de ingang.' },
    ],
    ritten: [
      { t: 'Den Haag naar Amsterdam', d: 'Voor afspraken, familiebezoek of een dagje stad.' },
      { t: 'Den Haag naar Schiphol', d: 'Voor vluchten, met bagage.' },
      { t: 'Den Haag naar Rotterdam', d: 'Van stad naar stad, via de A13.' },
      { t: 'Den Haag naar Leiden', d: 'Naar het noorden, voor zorg of familie.' },
      { t: 'Binnen Den Haag', d: 'Van huis naar dagbesteding of de huisarts.' },
    ],
    spoed: 'In Den Haag kan spoed nodig zijn bij een ontslag of onverwachte afspraak. Bel de spoedlijn met uw adres en bestemming, dan noemen we de aankomsttijd en de prijs.',
    bereik: 'De Haagse binnenstad heeft beveiligde zones en veel eenrichtingsverkeer. We spreken vooraf een ophaalpunt af waar de laadklep veilig kan worden uitgeklapt.',
    faqs: [
      { q: 'Rijden jullie ook naar Scheveningen?', a: 'Ja, voor een dagje aan zee halen we u op en brengen we u terug.' },
      { q: 'Kunnen jullie mij naar Schiphol brengen?', a: 'Ja, geef uw vluchtgegevens door, dan rekenen we terug vanaf de incheckdeadline.' },
      { q: 'Rijden jullie ook naar Rotterdam?', a: 'Ja, van Den Haag naar Rotterdam en terug.' },
      { q: 'Kan ik een vaste rit afspreken?', a: 'Ja, bijvoorbeeld voor dagbesteding of een terugkerende behandeling.' },
    ],
  },

  {
    slug: 'rotterdam',
    name: 'Rotterdam',
    region: 'Zuid-Holland en Utrecht',
    nearby: ['den-haag', 'leiden', 'utrecht', 'schiphol', 'amsterdam'],
    photo: { src: 'hero-nieuw-groenland.jpg', alt: 'Rolstoelbus voor de ingang van een gebouw', pos: 'center' },
    metaDescription: 'Rolstoeltaxi Rotterdam: rolstoelvervoer naar de Markthal, Ahoy, de Kuip en de zorg, vanuit Amsterdam en de regio. Laadklep, 24/7 spoedservice. Bel direct.',
    lead: 'Rotterdam is de havenstad met de Erasmusbrug, de Markthal en Ahoy. Voor een rolstoelrit betekent dat: brede straten, veel bezienswaardigheden en veel evenementen.',
    intro: [
      'Rotterdam heeft na de oorlog een nieuw centrum gebouwd, met brede straten en veel vlakke stukken. Dat is prettig voor een rolstoel, maar de afstanden zijn groot en de stad is druk bij evenementen.',
      'Wij rijden naar Rotterdam vanuit Amsterdam en de regio, en binnen de stad. Voor een spoedrit belt u direct, voor een evenement plannen we heen en terug in.',
    ],
    plekken: [
      { t: 'Rotterdam Centraal', d: 'Het grote station. Wij regelen het laatste stuk naar uw bestemming.' },
      { t: 'Markthal en Blaak', d: 'De bekende overdekte markt en het gebied eromheen. We zetten u af zo dicht mogelijk bij de ingang.' },
      { t: 'Erasmusbrug en Kop van Zuid', d: 'Het aanzicht van de stad, met het Wilhelminapier en Hotel New York.' },
      { t: 'Ahoy en De Kuip', d: 'Voor concerten en wedstrijden. We regelen heen en terug samen.' },
      { t: 'Kunsthal en het Museumpark', d: 'Musea in het centrum, goed bereikbaar.' },
      { t: 'Euromast en het Park', d: 'Een uitje met uitzicht over de haven.' },
    ],
    ritten: [
      { t: 'Rotterdam naar Den Haag', d: 'Via de A13, voor afspraken of familiebezoek.' },
      { t: 'Rotterdam naar Amsterdam', d: 'Van stad naar stad, voor een afspraak of dagje uit.' },
      { t: 'Rotterdam naar Schiphol', d: 'Voor vluchten, met bagage.' },
      { t: 'Rotterdam naar Utrecht', d: 'Naar het midden van het land.' },
      { t: 'Binnen Rotterdam', d: 'Van huis naar dagbesteding of een afspraak.' },
    ],
    spoed: 'In Rotterdam kan spoed nodig zijn bij een ontslag of onverwachte afspraak. Bel de spoedlijn met uw adres en bestemming, dan noemen we de aankomsttijd en de prijs.',
    bereik: 'Rotterdam heeft brede straten, maar ook tramrails en veel bouwwerkzaamheden. We spreken vooraf een ophaalpunt af waar de laadklep veilig kan worden uitgeklapt.',
    faqs: [
      { q: 'Kunnen jullie mij naar Ahoy of De Kuip brengen?', a: 'Ja, we plannen heen en terug samen in.' },
      { q: 'Rijden jullie ook naar Den Haag vanuit Rotterdam?', a: 'Ja, van Rotterdam naar Den Haag en terug.' },
      { q: 'Kunnen jullie mij naar Schiphol brengen?', a: 'Ja, geef uw vluchtgegevens door, dan rekenen we terug vanaf de incheckdeadline.' },
      { q: 'Kan ik een vaste rit afspreken?', a: 'Ja, bijvoorbeeld voor dagbesteding of een terugkerende behandeling.' },
    ],
  },

  {
    slug: 'utrecht',
    name: 'Utrecht',
    region: 'Zuid-Holland en Utrecht',
    nearby: ['amsterdam', 'rotterdam', 'den-haag', 'amstelveen', 'zwolle'],
    photo: { src: 'rolstoelbus-landgoed-poort.jpg', alt: 'Rolstoelbus bij een landgoedpoort van baksteen', pos: 'center' },
    metaDescription: 'Rolstoeltaxi Utrecht: rolstoelvervoer naar de Domtoren, het station, de Jaarbeurs en de zorg, vanuit Amsterdam. Elektrische laadklep, 24/7 spoedservice. Bel direct.',
    lead: 'Utrecht ligt midden in het land, met de Domtoren, de Oudegracht en het grootste station van Nederland. Voor een rolstoelrit betekent dat: veel verkeer, veel bezoekers en veel gemak.',
    intro: [
      'Utrecht is een knooppunt. Veel reizigers komen via het station aan en vertrekken van daaruit verder. Het centrum is autoluw, met de Oudegracht en de werven eromheen, wat voor een grote bus niet altijd handig is.',
      'Wij rijden naar Utrecht vanuit Amsterdam en de regio, en binnen de stad. Voor een spoedrit belt u direct, voor een vaste rit plannen we een schema.',
    ],
    plekken: [
      { t: 'Utrecht Centraal en Hoog Catharijne', d: 'Het grootste station van Nederland. Wij regelen het laatste stuk naar uw bestemming.' },
      { t: 'Domtoren en Domplein', d: 'Het symbool van de stad. We zetten u af zo dicht mogelijk bij het plein.' },
      { t: 'Oudegracht en de werven', d: 'Rustige straten langs het water, voor een uitje.' },
      { t: 'Jaarbeurs', d: 'Het beurzen- en congrescentrum naast het station. Voor evenementen plannen we heen en terug.' },
      { t: 'Museumkwartier en Rietveld Schröderhuis', d: 'Musea en architectuur, goed bereikbaar.' },
      { t: 'Utrecht Science Park', d: 'Het universiteits- en onderzoeksterrein. Voor werk en studie plannen we een vast schema.' },
    ],
    ritten: [
      { t: 'Utrecht naar Amsterdam', d: 'Van stad naar stad, voor afspraken of familie.' },
      { t: 'Utrecht naar Schiphol', d: 'Voor vluchten, met bagage.' },
      { t: 'Utrecht naar Rotterdam', d: 'Naar het zuiden, voor een afspraak of dagje uit.' },
      { t: 'Utrecht naar Den Haag', d: 'Naar de regeringsstad.' },
      { t: 'Binnen Utrecht', d: 'Van huis naar dagbesteding of een afspraak.' },
    ],
    spoed: 'In Utrecht kan spoed nodig zijn bij een ontslag of onverwachte afspraak. Bel de spoedlijn met uw adres en bestemming, dan noemen we de aankomsttijd en de prijs.',
    bereik: 'De Utrechtse binnenstad is deels autoluw en heeft veel fietsers. We spreken vooraf een ophaalpunt af waar de laadklep veilig kan worden uitgeklapt.',
    faqs: [
      { q: 'Kunnen jullie mij naar de Jaarbeurs brengen?', a: 'Ja, we plannen heen en terug samen in.' },
      { q: 'Rijden jullie ook vanuit Amsterdam naar Utrecht?', a: 'Ja, dat is een veelgevraagde rit voor afspraken en familiebezoek.' },
      { q: 'Kunnen jullie mij naar Schiphol brengen?', a: 'Ja, geef uw vluchtgegevens door, dan rekenen we terug vanaf de incheckdeadline.' },
      { q: 'Kan ik een vaste rit afspreken?', a: 'Ja, bijvoorbeeld voor dagbesteding of een terugkerende behandeling.' },
    ],
  },
];
