module.exports = [
  {
    slug: 'arnhem',
    name: 'Arnhem',
    region: 'Rest van Nederland',
    distant: true,
    nearby: ['nijmegen', 'utrecht', 'zwolle', 'eindhoven', 'amsterdam'],
    photo: { src: 'rolstoelbus-landgoed-poort.jpg', alt: 'Rolstoelbus bij een landgoedpoort tussen bomen', pos: 'center' },
    metaDescription: 'Rolstoeltaxi Arnhem: rolstoelvervoer van en naar Arnhem, naar het Openluchtmuseum, Sonsbeek en de zorg. Elektrische laadklep, 24/7 spoedservice. Bel direct.',
    lead: 'Arnhem ligt aan de Rijn, met park Sonsbeek, het Openluchtmuseum en Burgers\' Zoo. Voor een langere rit met een rolstoel is het fijn om te weten dat u rechtstreeks wordt gebracht.',
    intro: [
      'Arnhem is de hoofdstad van Gelderland, met veel groen en een heuvelachtige omgeving. Wie vanuit Amsterdam of Utrecht naar Arnhem moet, reist een flink stuk. Met de trein is een rolstoelrit vaak een reeks overstappen; met een rolstoelbus rijdt u rechtstreeks.',
      'Wij rijden ritten naar en vanuit Arnhem: voor een afspraak, een familiebezoek of een dagje uit. Bij lange ritten bespreken we vooraf de reistijd en de pauzes.',
    ],
    plekken: [
      { t: 'Arnhem Centraal', d: 'Het station in het centrum. We spreken vooraf de ingang af die voor u het meest toegankelijk is.' },
      { t: 'Nederlands Openluchtmuseum', d: 'Een groot buitenmuseum, geschikt voor een scootmobiel. We regelen heen en terug.' },
      { t: 'Burgers\' Zoo', d: 'Een dagje dieren kijken. We zetten u af bij een toegankelijke ingang.' },
      { t: 'Park Sonsbeek', d: 'Een groot park in het centrum, voor een rustige wandeling.' },
      { t: 'GelreDome', d: 'Het stadion, voor wedstrijden en concerten. We plannen heen en terug samen in.' },
      { t: 'Airborne Museum in Oosterbeek', d: 'Vlak bij Arnhem, over de Slag om Arnhem. Goed bereikbaar.' },
    ],
    ritten: [
      { t: 'Arnhem naar Amsterdam', d: 'Een langere rit naar de hoofdstad, voor afspraken of familie.' },
      { t: 'Arnhem naar Utrecht', d: 'Naar het midden van het land.' },
      { t: 'Arnhem naar Schiphol', d: 'Voor vluchten, ruim op tijd.' },
      { t: 'Arnhem naar Nijmegen', d: 'Van Rijn naar Waal, in Gelderland.' },
      { t: 'Binnen Arnhem', d: 'Van huis naar dagbesteding of een afspraak.' },
    ],
    spoed: 'Ook voor ritten naar Arnhem kan spoed nodig zijn. Bel de spoedlijn met uw adres en bestemming, dan noemen we de aankomsttijd en de prijs. Bij een lange afstand hoort u eerlijk hoe lang de rit duurt.',
    bereik: 'Voor ritten naar en vanuit Arnhem spreken we vooraf de tijd en het ophaalpunt af. Bij lange ritten bespreken we of er een pauze nodig is, en hoe u die wilt invullen.',
    faqs: [
      { q: 'Rijden jullie ook lange ritten naar Arnhem?', a: 'Ja, we rijden ritten in Nederland. Bij een lange afstand bespreken we vooraf de reistijd en pauzes.' },
      { q: 'Kunnen jullie mij naar het Openluchtmuseum brengen?', a: 'Ja, heen en terug op een afgesproken tijd.' },
      { q: 'Wat kost een rit naar Arnhem?', a: 'De prijs hangt af van de afstand en het tijdstip. U hoort de prijs altijd vooraf aan de telefoon.' },
      { q: 'Kan ik ook een terugrit boeken?', a: 'Ja, we plannen heen en terug samen in.' },
    ],
  },

  {
    slug: 'nijmegen',
    name: 'Nijmegen',
    region: 'Rest van Nederland',
    distant: true,
    nearby: ['arnhem', 'eindhoven', 'utrecht', 'maastricht', 'amsterdam'],
    photo: { src: 'rolstoelbus-zijkant.jpg', alt: 'Rolstoelbus, zijaanzicht, geparkeerd', pos: 'center' },
    metaDescription: 'Rolstoeltaxi Nijmegen: rolstoelvervoer van en naar Nijmegen, naar de Waalkade, de universiteit en de zorg. Laadklep, 24/7 spoedservice. Bel direct.',
    lead: 'Nijmegen is de oudste stad van Nederland, aan de Waal, met het Valkhof en de Vierdaagse. Voor een lange rit met een rolstoel rijdt u rechtstreeks.',
    intro: [
      'Nijmegen is een levendige stad met veel studenten, een gezellige binnenstad en de Waalkade. In juli is de stad in de ban van de Vierdaagse, en dat betekent afgesloten wegen en veel drukte.',
      'Wij rijden ritten naar en vanuit Nijmegen. Bij een lange afstand plannen we ruim, bespreken we de reistijd en stemmen we af waar u wordt opgehaald.',
    ],
    plekken: [
      { t: 'Station Nijmegen', d: 'Het knooppunt in het centrum. We spreken vooraf een toegankelijke ingang af.' },
      { t: 'Waalkade en de Waalbrug', d: 'De rivierkant van de stad, met terrassen en uitzicht.' },
      { t: 'Valkhof en het Museum Het Valkhof', d: 'Een historische plek met een museum. Goed bereikbaar.' },
      { t: 'Grote Markt', d: 'Het plein in het centrum. Rond het plein zijn straten autoluw.' },
      { t: 'Goffertpark', d: 'Een groot park met een stadion, voor een wedstrijd of een wandeling.' },
      { t: 'Radboud Universiteit', d: 'Het universiteitsterrein. Voor werk en studie plannen we een vast schema.' },
    ],
    ritten: [
      { t: 'Nijmegen naar Amsterdam', d: 'Een lange rit naar de hoofdstad, voor afspraken of familie.' },
      { t: 'Nijmegen naar Utrecht', d: 'Naar het midden van het land.' },
      { t: 'Nijmegen naar Eindhoven', d: 'Naar het zuiden, voor werk of zorg.' },
      { t: 'Nijmegen naar Schiphol', d: 'Voor vluchten, ruim op tijd.' },
      { t: 'Binnen Nijmegen', d: 'Van huis naar dagbesteding of een afspraak.' },
    ],
    spoed: 'Ook voor ritten naar Nijmegen kan spoed nodig zijn. Bel de spoedlijn met uw adres en bestemming, dan noemen we de aankomsttijd en de prijs.',
    bereik: 'Tijdens de Vierdaagse zijn veel wegen afgesloten. Reist u dan, bel ruim van tevoren, dan bespreken we de afzetplek en de route.',
    faqs: [
      { q: 'Rijden jullie ook lange ritten naar Nijmegen?', a: 'Ja, we rijden ritten in Nederland. Bij een lange afstand bespreken we vooraf de reistijd.' },
      { q: 'Wat als de Vierdaagse plaatsvindt?', a: 'Plan dan ruim van tevoren. Wegen zijn afgesloten en we spreken een afzetplek en ophaaltijd af.' },
      { q: 'Wat kost een rit naar Nijmegen?', a: 'De prijs hangt af van afstand en tijdstip. U hoort de prijs vooraf aan de telefoon.' },
      { q: 'Kan ik ook een terugrit boeken?', a: 'Ja, we plannen heen en terug samen in.' },
    ],
  },

  {
    slug: 'eindhoven',
    name: 'Eindhoven',
    region: 'Rest van Nederland',
    distant: true,
    nearby: ['nijmegen', 'maastricht', 'utrecht', 'rotterdam', 'amsterdam'],
    photo: { src: 'rolstoelbus-laadklep-hoogbouw.jpg', alt: 'Rolstoelbus met uitgeklapte laadklep, hoogbouw op de achtergrond', pos: 'center' },
    metaDescription: 'Rolstoeltaxi Eindhoven: rolstoelvervoer van en naar Eindhoven, naar het station, de luchthaven en de zorg. Laadklep, 24/7 spoedservice. Bel direct.',
    lead: 'Eindhoven is de stad van Philips, PSV en design. Voor een lange rit met een rolstoel rijdt u rechtstreeks, zonder overstappen.',
    intro: [
      'Eindhoven is een moderne stad met veel techniek, een groot ziekenhuis en een vliegveld. Wie vanuit Amsterdam of Utrecht naar Eindhoven moet, heeft een flinke rit voor de boeg, en met een rolstoel is een treinreis lastig.',
      'Wij rijden ritten naar en vanuit Eindhoven. Bij een lange afstand plannen we ruim, bespreken we de reistijd en stemmen we af waar u wordt opgehaald.',
    ],
    plekken: [
      { t: 'Eindhoven Centraal', d: 'Het station in het centrum. We spreken vooraf een toegankelijke ingang af.' },
      { t: 'Philips Stadion', d: 'De thuisbasis van PSV. Voor wedstrijden plannen we heen en terug samen in.' },
      { t: 'Strijp-S en de Design Academy', d: 'De creatieve wijk van de stad, met veel horeca.' },
      { t: 'Evoluon', d: 'Het bekende gebouw dat op een vliegende schotel lijkt.' },
      { t: 'Eindhoven Airport', d: 'Voor vluchten vanaf Eindhoven. We helpen met bagage.' },
      { t: 'High Tech Campus', d: 'Het grote bedrijventerrein. Voor werk plannen we een vast schema.' },
    ],
    ritten: [
      { t: 'Eindhoven naar Amsterdam', d: 'Een lange rit naar de hoofdstad, voor afspraken of familie.' },
      { t: 'Eindhoven naar Utrecht', d: 'Naar het midden van het land.' },
      { t: 'Eindhoven naar Maastricht', d: 'Naar het zuiden.' },
      { t: 'Eindhoven naar Schiphol', d: 'Voor vluchten vanaf Schiphol.' },
      { t: 'Binnen Eindhoven', d: 'Van huis naar dagbesteding of een afspraak.' },
    ],
    spoed: 'Ook voor ritten naar Eindhoven kan spoed nodig zijn. Bel de spoedlijn met uw adres en bestemming, dan noemen we de aankomsttijd en de prijs.',
    bereik: 'Eindhoven is ruim opgezet, met brede wegen. De meeste adressen zijn goed bereikbaar. In het centrum en rond het station spreken we vooraf een ophaalpunt af.',
    faqs: [
      { q: 'Rijden jullie ook lange ritten naar Eindhoven?', a: 'Ja, we rijden ritten in Nederland. Bij een lange afstand bespreken we vooraf de reistijd.' },
      { q: 'Kunnen jullie mij naar Eindhoven Airport brengen?', a: 'Ja, we brengen u tot bij de terminal en helpen met de bagage.' },
      { q: 'Wat kost een rit naar Eindhoven?', a: 'De prijs hangt af van afstand en tijdstip. U hoort de prijs vooraf aan de telefoon.' },
      { q: 'Kan ik ook een terugrit boeken?', a: 'Ja, we plannen heen en terug samen in.' },
    ],
  },

  {
    slug: 'groningen',
    name: 'Groningen',
    region: 'Rest van Nederland',
    distant: true,
    nearby: ['zwolle', 'arnhem', 'utrecht', 'amsterdam', 'alkmaar'],
    photo: { src: 'rolstoelbus-baksteen-laadklep.jpg', alt: 'Rolstoelbus met laadklep voor een gebouw van rode baksteen', pos: 'center' },
    metaDescription: 'Rolstoeltaxi Groningen: rolstoelvervoer van en naar Groningen, naar de Grote Markt, het Groninger Museum en de zorg. Laadklep, 24/7 spoedservice. Bel direct.',
    lead: 'Groningen is de hoofdstad van het noorden, met de Martinitoren, een levendige binnenstad en veel studenten. Voor een lange rit met een rolstoel rijdt u rechtstreeks.',
    intro: [
      'Groningen ligt ver van Amsterdam, ruim twee uur rijden of langer. Met de trein is dat een reis met overstappen, en voor iemand in een rolstoel is dat vaak te veel gedoe. Een rolstoelbus rijdt rechtstreeks, van deur tot deur.',
      'Wij rijden ritten naar en vanuit Groningen, voor zorg, familie of een uitje. Bij lange ritten bespreken we vooraf de reistijd en de pauzes, en plannen we ruim.',
    ],
    plekken: [
      { t: 'Groningen Hoofdstation', d: 'Het station bij het centrum. We spreken vooraf een toegankelijke ingang af.' },
      { t: 'Grote Markt en Martinitoren', d: 'Het hart van de stad. Rond de Grote Markt is veel autoluw.' },
      { t: 'Groninger Museum', d: 'Het opvallende museum bij het station. Goed bereikbaar.' },
      { t: 'Forum Groningen', d: 'Het grote culturele gebouw aan de Grote Markt.' },
      { t: 'Noorderplantsoen', d: 'Een groot park bij het centrum, voor een wandeling.' },
      { t: 'Universiteit en het Zernike-terrein', d: 'Voor werk en studie plannen we een vast schema.' },
    ],
    ritten: [
      { t: 'Groningen naar Amsterdam', d: 'Een lange rit naar de hoofdstad, voor afspraken of familie.' },
      { t: 'Groningen naar Zwolle', d: 'Naar het zuiden, langs de A28.' },
      { t: 'Groningen naar Utrecht', d: 'Naar het midden van het land.' },
      { t: 'Groningen naar Schiphol', d: 'Voor vluchten, ruim op tijd.' },
      { t: 'Binnen Groningen', d: 'Van huis naar dagbesteding of een afspraak.' },
    ],
    spoed: 'Ook voor ritten naar Groningen kan spoed nodig zijn. Bel de spoedlijn met uw adres en bestemming, dan noemen we de aankomsttijd en de prijs. Bij een lange afstand hoort u eerlijk hoe lang de rit duurt.',
    bereik: 'Bij lange ritten spreken we vooraf de tijd en het ophaalpunt af, en bespreken we of er een pauze nodig is. In de binnenstad van Groningen is veel autoluw, dus we kiezen een ophaalpunt in de buurt.',
    faqs: [
      { q: 'Rijden jullie ook naar Groningen?', a: 'Ja, we rijden ritten in Nederland. Bij een lange afstand bespreken we vooraf de reistijd en pauzes.' },
      { q: 'Wat kost een rit naar Groningen?', a: 'De prijs hangt af van afstand en tijdstip. U hoort de prijs vooraf aan de telefoon.' },
      { q: 'Kan ik ook een terugrit boeken?', a: 'Ja, we plannen heen en terug samen in.' },
      { q: 'Kan een begeleider meerijden?', a: 'Ja, een begeleider rijdt gewoon mee in de bus.' },
    ],
  },

  {
    slug: 'zwolle',
    name: 'Zwolle',
    region: 'Rest van Nederland',
    distant: true,
    nearby: ['groningen', 'arnhem', 'utrecht', 'amsterdam', 'nijmegen'],
    photo: { src: 'scootmobiel-laadklep.jpg', alt: 'Scootmobiel op de laadklep van de rolstoelbus', pos: 'center' },
    metaDescription: 'Rolstoeltaxi Zwolle: rolstoelvervoer van en naar Zwolle, naar de Sassenpoort, het museum en de zorg. Elektrische laadklep, 24/7 spoedservice. Bel direct.',
    lead: 'Zwolle is een Hanzestad met een historisch centrum, de Sassenpoort en het Museum de Fundatie. Voor een lange rit met een rolstoel rijdt u rechtstreeks.',
    intro: [
      'Zwolle ligt aan de IJssel, op de grens van Overijssel en Gelderland. Het centrum is compact en grotendeels autoluw, met veel historische gebouwen. Wie vanuit Amsterdam naar Zwolle moet, heeft een rit van ruim een uur of langer.',
      'Wij rijden ritten naar en vanuit Zwolle, voor zorg, familie of een uitje. We plannen ruim en spreken vooraf af waar u wordt opgehaald.',
    ],
    plekken: [
      { t: 'Station Zwolle', d: 'Een belangrijk knooppunt. We spreken vooraf een toegankelijke ingang af.' },
      { t: 'Sassenpoort', d: 'De bekende stadspoort. Goed bereikbaar.' },
      { t: 'Museum de Fundatie', d: 'Het museum met de opvallende koepel. We regelen heen en terug.' },
      { t: 'Grote Kerk en het centrum', d: 'Het historische hart van de stad. Grotendeels autoluw.' },
      { t: 'Diezerpoort en de binnenstad', d: 'Winkels en horeca in de oude binnenstad.' },
      { t: 'IJsselhallen', d: 'Een beurs- en evenementenlocatie. Voor evenementen plannen we heen en terug.' },
    ],
    ritten: [
      { t: 'Zwolle naar Amsterdam', d: 'Een langere rit naar de hoofdstad, voor afspraken of familie.' },
      { t: 'Zwolle naar Utrecht', d: 'Naar het midden van het land.' },
      { t: 'Zwolle naar Groningen', d: 'Naar het noorden.' },
      { t: 'Zwolle naar Schiphol', d: 'Voor vluchten, ruim op tijd.' },
      { t: 'Binnen Zwolle', d: 'Van huis naar dagbesteding of een afspraak.' },
    ],
    spoed: 'Ook voor ritten naar Zwolle kan spoed nodig zijn. Bel de spoedlijn met uw adres en bestemming, dan noemen we de aankomsttijd en de prijs.',
    bereik: 'Het centrum van Zwolle is grotendeels autoluw, dus we spreken vooraf een ophaalpunt in de buurt af. Buiten het centrum is de bus doorgaans tot voor de deur.',
    faqs: [
      { q: 'Rijden jullie ook lange ritten naar Zwolle?', a: 'Ja, we rijden ritten in Nederland. Bij een lange afstand bespreken we vooraf de reistijd.' },
      { q: 'Kunnen jullie mij naar het museum brengen?', a: 'Ja, heen en terug op een afgesproken tijd.' },
      { q: 'Wat kost een rit naar Zwolle?', a: 'De prijs hangt af van afstand en tijdstip. U hoort de prijs vooraf aan de telefoon.' },
      { q: 'Kan ik ook een terugrit boeken?', a: 'Ja, we plannen heen en terug samen in.' },
    ],
  },

  {
    slug: 'maastricht',
    name: 'Maastricht',
    region: 'Rest van Nederland',
    distant: true,
    nearby: ['eindhoven', 'nijmegen', 'utrecht', 'rotterdam', 'amsterdam'],
    photo: { src: 'rolstoelbus-voorkant.jpg', alt: 'Rolstoelbus in de zon voor een gebouw', pos: 'center 55%' },
    metaDescription: 'Rolstoeltaxi Maastricht: rolstoelvervoer van en naar Maastricht, naar het Vrijthof, het station en de zorg. Elektrische laadklep, 24/7 spoedservice. Bel direct.',
    lead: 'Maastricht ligt helemaal in het zuiden, aan de Maas, met het Vrijthof en de Sint-Servaasbasiliek. Voor een lange rit met een rolstoel rijdt u rechtstreeks.',
    intro: [
      'Maastricht is een van de mooiste steden van Nederland, met een gezellige binnenstad, veel terrassen en de Maas. Het ligt ver van Amsterdam, ruim drie uur rijden. Met de trein is dat een lange reis met overstappen.',
      'Wij rijden ritten naar en vanuit Maastricht, voor zorg, familie of een uitje. Bij lange ritten plannen we ruim, en bespreken we vooraf de reistijd en de pauzes.',
    ],
    plekken: [
      { t: 'Station Maastricht', d: 'Het station aan de Maas. We spreken vooraf een toegankelijke ingang af.' },
      { t: 'Vrijthof en Sint-Servaasbasiliek', d: 'Het grote plein in het centrum, met terrassen en de basiliek.' },
      { t: 'Onze Lieve Vrouweplein', d: 'Een gezellig plein in het centrum.' },
      { t: 'Sint Servaasbrug', d: 'De oude brug over de Maas, tussen centrum en Wyck.' },
      { t: 'Bonnefantenmuseum', d: 'Het museum aan de Maas. We regelen heen en terug.' },
      { t: 'MECC Maastricht', d: 'Het beurs- en congrescentrum. Voor evenementen plannen we heen en terug.' },
    ],
    ritten: [
      { t: 'Maastricht naar Amsterdam', d: 'Een lange rit naar de hoofdstad, voor afspraken of familie.' },
      { t: 'Maastricht naar Eindhoven', d: 'Naar het noorden.' },
      { t: 'Maastricht naar Utrecht', d: 'Naar het midden van het land.' },
      { t: 'Maastricht naar Schiphol', d: 'Voor vluchten, ruim op tijd.' },
      { t: 'Binnen Maastricht', d: 'Van huis naar dagbesteding of een afspraak.' },
    ],
    spoed: 'Ook voor ritten naar Maastricht kan spoed nodig zijn. Bel de spoedlijn met uw adres en bestemming, dan noemen we de aankomsttijd en de prijs. Bij een lange afstand hoort u eerlijk hoe lang de rit duurt.',
    bereik: 'Het centrum van Maastricht is autoluw, met veel terrassen en kasseien. We spreken vooraf een ophaalpunt in de buurt af waar de laadklep veilig kan worden uitgeklapt.',
    faqs: [
      { q: 'Rijden jullie ook naar Maastricht?', a: 'Ja, we rijden ritten in Nederland. Bij een lange afstand bespreken we vooraf de reistijd en pauzes.' },
      { q: 'Wat kost een rit naar Maastricht?', a: 'De prijs hangt af van afstand en tijdstip. U hoort de prijs vooraf aan de telefoon.' },
      { q: 'Kan ik ook een terugrit boeken?', a: 'Ja, we plannen heen en terug samen in.' },
      { q: 'Kan een begeleider meerijden?', a: 'Ja, een begeleider rijdt gewoon mee in de bus.' },
    ],
  },
];
