module.exports = [
  {
    slug: 'haarlem',
    name: 'Haarlem',
    region: 'Kennemerland en Noord-Holland',
    nearby: ['heemstede', 'zandvoort', 'amsterdam', 'ijmuiden', 'beverwijk'],
    photo: { src: 'haarlem-grote-markt.jpg', alt: 'Rolstoelbus met uitgeklapte laadklep op de Grote Markt in Haarlem, naast het standbeeld van Laurens Janszoon Coster', pos: 'center 58%' },
    portrait: true,
    metaDescription: 'Rolstoeltaxi Haarlem met spoedservice: rolstoelvervoer in de binnenstad, naar Amsterdam, Schiphol en de kust. Elektrische laadklep, 24/7 bereikbaar. Bel direct.',
    lead: 'Haarlem heeft een prachtige binnenstad vol kasseien, grachten en smalle straten. Voor een rolstoelrit is dat een uitdaging die wij kennen, van de Grote Markt tot de Spaarne.',
    intro: [
      'De Grote Markt met het standbeeld van Laurens Janszoon Coster, de Sint-Bavokerk en het Stadhuis: dit is het hart van Haarlem, en het is ook de plek waar onze bus regelmatig staat. Op de foto op deze pagina ziet u hem met uitgeklapte laadklep op het plein, precies zoals we werken.',
      'Een rit in Haarlem begint bij het vinden van de juiste plek. In de binnenstad zijn straten autoluw, sommige bruggen laag en de kasseien onprettig voor een rolstoel. Wij spreken vooraf af waar we u ophalen, zodat u zo min mogelijk over de stenen hoeft.',
    ],
    plekken: [
      { t: 'Grote Markt en Sint-Bavokerk', d: 'Het plein in het centrum. We zetten u zo dicht mogelijk bij het gewenste terras, de kerk of het museum af.' },
      { t: 'Frans Hals Museum en Teylers Museum', d: 'Twee bekende musea, beide goed bereikbaar. We regelen heen en terug in één keer.' },
      { t: 'Station Haarlem', d: 'Aansluiting op de trein. Wij helpen bij de aansluiting als het openbaar vervoer niet lukt.' },
      { t: 'Spaarne en de Bakenessergracht', d: 'Rustige wandelroutes langs het water. Voor een dagje uit halen we u op en brengen we u terug.' },
      { t: 'Haarlemmerhout en Kenaupark', d: 'Twee groene plekken vlak bij het centrum, voor een wandeling met een scootmobiel of rolstoel.' },
      { t: 'Haarlem-Noord en Schalkwijk', d: 'Grote woonwijken met veel senioren. We halen u op aan de deur en helpen over drempels.' },
    ],
    ritten: [
      { t: 'Haarlem naar Amsterdam', d: 'Voor afspraken, familiebezoek of een dagje stad.' },
      { t: 'Haarlem naar Schiphol', d: 'Vroege vluchten zijn geen probleem: we zijn dag en nacht bereikbaar.' },
      { t: 'Haarlem naar Zandvoort', d: 'Een dagje naar het strand, met scootmobiel of rolstoel.' },
      { t: 'Haarlem naar Heemstede', d: 'Een korte rit voor de winkels aan de Binnenweg of familie.' },
      { t: 'Binnen Haarlem', d: 'Van huis naar dagbesteding, de huisarts of een afspraak in een andere wijk.' },
    ],
    spoed: 'In Haarlem komt spoed vaak voort uit een situatie thuis of in een zorginstelling: een val, een ontslag of een afspraak die naar voren is gehaald. Bel de spoedlijn met uw adres en bestemming, dan noemen we bij het eerste telefoontje de aankomsttijd en de prijs.',
    bereik: 'De binnenstad is deels autoluw en heeft veel kasseien. Buiten het centrum is het eenvoudiger: daar rijdt de bus doorgaans tot voor de deur. We bespreken vooraf waar u wordt opgehaald, zodat de laadklep veilig kan worden uitgeklapt.',
    faqs: [
      { q: 'Kan de bus in de Haarlemse binnenstad komen?', a: 'Tot vlak bij de bestemming meestal wel. In autoluwe straten spreken we vooraf een ophaalpunt af waar de laadklep veilig kan worden uitgeklapt.' },
      { q: 'Rijden jullie ook naar het strand van Zandvoort?', a: 'Ja, voor een dagje uit halen we u op en brengen u terug op een afgesproken tijd.' },
      { q: 'Kan ik vanuit Haarlem naar Schiphol worden gebracht?', a: 'Ja, ook voor vroege vluchten. Geef uw vluchtgegevens door, dan rekenen we terug vanaf de incheckdeadline.' },
      { q: 'Kan ik een vaste rit afspreken?', a: 'Ja, bijvoorbeeld voor dagbesteding of een terugkerende behandeling.' },
    ],
  },

  {
    slug: 'heemstede',
    name: 'Heemstede',
    region: 'Kennemerland en Noord-Holland',
    nearby: ['haarlem', 'zandvoort', 'hoofddorp', 'amsterdam', 'leiden'],
    photo: { src: 'rolstoelbus-zorginstelling.jpg', alt: 'Rolstoelbus voor een woon- en zorggebouw', pos: 'center' },
    metaDescription: 'Rolstoeltaxi Heemstede: rolstoelvervoer in Heemstede en Aerdenhout, naar Haarlem, Amsterdam en Schiphol. Elektrische laadklep, 24/7 spoedservice. Bel direct.',
    lead: 'Heemstede ligt naast Haarlem, met veel groen en een sterke gemeenschap van senioren. Voor een rolstoelrit betekent dat: veel ritten naar zorg, winkels en familie.',
    intro: [
      'Heemstede is een rustige, groene plaats. Veel inwoners zijn ouder en wonen zelfstandig of in een zorgcomplex. Voor hen is een betrouwbare rit naar de huisarts, de kapper of familie geen luxe maar een dagelijkse noodzaak.',
      'Rolstoeltaxi Spoed rijdt in Heemstede en Aerdenhout, en naar Haarlem, Amsterdam en Schiphol. Voor spoed belt u direct, voor vaste ritten maken we een schema.',
    ],
    plekken: [
      { t: 'Binnenweg', d: 'De winkelstraat van Heemstede. We zetten u af waar u zo dicht mogelijk bij uw bestemming bent.' },
      { t: 'Station Heemstede-Aerdenhout', d: 'Aansluiting op de trein richting Haarlem en Leiden. Wij regelen het laatste stuk.' },
      { t: 'Groenendaal', d: 'Een groot park aan de rand van Heemstede, voor een wandeling met scootmobiel of rolstoel.' },
      { t: 'Heemsteedse Dreef', d: 'Een van de mooiste lanen van de regio. Voor een dagje uit halen we u op.' },
      { t: 'Woon- en zorgcomplexen', d: 'Veel inwoners wonen in een complex. De chauffeur helpt tot in de gang.' },
      { t: 'Aerdenhout', d: 'Het dorp ten noorden van Heemstede, dat we ook bedienen.' },
    ],
    ritten: [
      { t: 'Heemstede naar Haarlem', d: 'Naar het centrum of een afspraak in het ziekenhuis in Haarlem.' },
      { t: 'Heemstede naar Amsterdam', d: 'Voor familiebezoek, een museum of een afspraak.' },
      { t: 'Heemstede naar Schiphol', d: 'Rechtstreeks naar de vertrekhal.' },
      { t: 'Heemstede naar Zandvoort', d: 'Een dagje naar het strand.' },
      { t: 'Binnen Heemstede', d: 'Van huis naar dagbesteding, de huisarts of de kapper.' },
    ],
    spoed: 'Omdat Heemstede dicht bij Haarlem ligt, kunnen onze bussen doorgaans snel bij u zijn. Bel de spoedlijn met uw adres en bestemming, dan noemen we de aankomsttijd en de prijs.',
    bereik: 'De straten in Heemstede zijn ruim en de meeste adressen zijn goed bereikbaar. Bij een zorgcomplex met een eigen ingang of oprit spreken we af waar de bus het beste kan stoppen.',
    faqs: [
      { q: 'Rijden jullie ook in Aerdenhout?', a: 'Ja, Aerdenhout valt binnen ons werkgebied.' },
      { q: 'Kunnen jullie mij bij een zorgcomplex ophalen?', a: 'Ja, de chauffeur helpt tot in de gang of lift. Geef bij het boeken aan hoe de toegang is.' },
      { q: 'Kan ik een wekelijkse rit naar dagbesteding afspreken?', a: 'Ja, we plannen terugkerende ritten graag in.' },
      { q: 'Rijden jullie ook in het weekend?', a: 'Ja, we zijn 24/7 bereikbaar.' },
    ],
  },

  {
    slug: 'zandvoort',
    name: 'Zandvoort',
    region: 'Kennemerland en Noord-Holland',
    nearby: ['haarlem', 'heemstede', 'ijmuiden', 'amsterdam', 'hoofddorp'],
    photo: { src: 'rolstoelbus-voorkant.jpg', alt: 'Rolstoelbus in de zon voor een gebouw', pos: 'center 55%' },
    metaDescription: 'Rolstoeltaxi Zandvoort: rolstoelvervoer naar het strand, het circuit en de kern, vanuit Haarlem en Amsterdam. Elektrische laadklep, 24/7 bereikbaar. Bel direct.',
    lead: 'Zandvoort is strand, circuit en een kust die veel bezoekers trekt. Voor een rolstoel is het aanpassen aan drukte en afgesloten wegen: precies waarvoor u ons belt.',
    intro: [
      'Zandvoort heeft een breed strand, een boulevard en een dorpskern die op zomerse dagen vol loopt. Ook rond raceweekenden op het circuit zijn straten afgesloten en is het openbaar vervoer overbelast. Voor iemand in een rolstoel is dat de dag waarop je niet wilt gokken.',
      'Wij zoeken vooraf uit waar u het beste kunt uitstappen en op welk tijdstip we u ophalen. Op drukke dagen bespreken we ruim van tevoren de mogelijkheden.',
    ],
    plekken: [
      { t: 'Strand en boulevard', d: 'Een dagje aan zee. We zetten u af bij een toegankelijke strandopgang en spreken een ophaaltijd af.' },
      { t: 'Circuit Zandvoort', d: 'Voor de racedagen. Straten zijn dan afgesloten, dus vooraf plannen is nodig.' },
      { t: 'Station Zandvoort aan Zee', d: 'Het eindpunt van de trein vanaf Haarlem. Wij regelen het stuk naar uw bestemming.' },
      { t: 'Gasthuisplein en de kern', d: 'Winkels en terrassen in het dorp. We spreken een toegankelijke afzetplek af.' },
      { t: 'Nationaal Park Zuid-Kennemerland', d: 'Duinen en wandelpaden, voor wie een rustig dagje uit wil.' },
      { t: 'Woonwijken en zorgcomplexen', d: 'Ook inwoners halen we op, voor afspraken en familiebezoek.' },
    ],
    ritten: [
      { t: 'Zandvoort naar Haarlem', d: 'Voor afspraken en zorg in de binnenstad.' },
      { t: 'Zandvoort naar Amsterdam', d: 'Een dagje de stad in, of terug naar huis.' },
      { t: 'Zandvoort naar Schiphol', d: 'Voor vluchten vanaf Schiphol, met bagage.' },
      { t: 'Amsterdam naar Zandvoort', d: 'Een dagje naar het strand, met rolstoel of scootmobiel.' },
      { t: 'Binnen Zandvoort', d: 'Korte ritten voor inwoners, bijvoorbeeld naar de huisarts.' },
    ],
    spoed: 'Ook in Zandvoort kan spoed nodig zijn, bijvoorbeeld bij een ontslag of een plotselinge afspraak. Bel de spoedlijn, dan noemen we de aankomsttijd en de prijs. Op drukke dagen kunnen straten afgesloten zijn en houden we daar rekening mee.',
    bereik: 'Op een zonnige dag of tijdens een evenement is Zandvoort moeilijk bereikbaar. Wij plannen dan een vaste afzetplek en ophaaltijd, zodat u niet hoeft te improviseren.',
    faqs: [
      { q: 'Kan ik met een scootmobiel naar het strand?', a: 'Ja, we zetten u af bij een toegankelijke opgang. Voor het strand zelf heeft u eventueel een aangepaste strandrolstoel nodig; vraag dat na bij de strandpaviljoens.' },
      { q: 'Wat als er een evenement op het circuit is?', a: 'Plan dan ruim van tevoren. Straten zijn afgesloten en we spreken een vaste afzetplek en ophaaltijd af.' },
      { q: 'Rijden jullie ook \'s avonds terug?', a: 'Ja, we zijn 24/7 bereikbaar. We plannen de terugrit vooraf in.' },
      { q: 'Kunnen jullie mij vanuit Amsterdam naar Zandvoort brengen?', a: 'Ja, dat is een veelgevraagde rit voor een dagje uit.' },
    ],
  },

  {
    slug: 'ijmuiden',
    name: 'IJmuiden',
    region: 'Kennemerland en Noord-Holland',
    nearby: ['beverwijk', 'haarlem', 'zandvoort', 'amsterdam', 'zaandam'],
    photo: { src: 'luchthavenvervoer-bagage.jpg', alt: 'Rolstoelbus met laadklep op een kade bij een groot schip, reizigers met bagage op de achtergrond', pos: 'center' },
    metaDescription: 'Rolstoeltaxi IJmuiden: rolstoelvervoer naar de zeehaven, de cruiseterminal en het strand, vanuit Amsterdam en Haarlem. Bagage, laadklep, 24/7 bereikbaar.',
    lead: 'IJmuiden is een havenstad aan de Noordzee, met een cruiseterminal, een strand en veel industrie. Voor een rolstoelreiziger is het vooral een plek waar de rit naar de kade erg belangrijk is.',
    intro: [
      'De zeehaven van IJmuiden ontvangt jaarlijks cruiseschepen en veerboten. Reizigers met een rolstoel of scootmobiel moeten op een vaste tijd aan boord of van boord, en dat vraagt om een betrouwbare rit met ruimte voor bagage.',
      'Naast de haven is er het strand, het centrum en de wijk Velsen-Zuid. Ook voor inwoners rijden we: naar afspraken, familie en dagbesteding.',
    ],
    plekken: [
      { t: 'Cruiseterminal IJmuiden', d: 'Voor in- en uitschepen. We spreken een vaste tijd en plek af, met ruimte voor koffers en rolstoel.' },
      { t: 'Zeehaven en sluizen', d: 'Het industriële hart van IJmuiden. Voor werk of een bezoek rijden we u erheen.' },
      { t: 'Strand en Kennemerstrand', d: 'Een dagje aan zee vanuit Amsterdam of Haarlem.' },
      { t: 'Centrum IJmuiden', d: 'Winkels en voorzieningen. We spreken een toegankelijke afzetplek af.' },
      { t: 'Velsen-Zuid en Driehuis', d: 'Woonwijken waar we regelmatig ophalen.' },
      { t: 'Noordzeekanaal en de pier', d: 'Voor een wandeling langs het water met scootmobiel of rolstoel.' },
    ],
    ritten: [
      { t: 'Amsterdam naar IJmuiden', d: 'Voor een cruise, een dagje uit of een afspraak.' },
      { t: 'IJmuiden naar Schiphol', d: 'Voor reizigers die na een cruise doorvliegen.' },
      { t: 'IJmuiden naar Haarlem', d: 'Van kust naar stad.' },
      { t: 'IJmuiden naar Beverwijk', d: 'Een korte rit langs het kanaal, bijvoorbeeld naar familie of de winkels.' },
      { t: 'Binnen IJmuiden', d: 'Van huis naar dagbesteding of de huisarts.' },
    ],
    spoed: 'Bij een cruise of veerboot is de tijd bepalend. Een gemiste aansluiting kan de hele reis kosten. Bel de spoedlijn met de vertrektijd van het schip, dan rekenen we terug en noemen we meteen de prijs.',
    bereik: 'De haven is groot en de terminal ligt op een vaste plek. We spreken vooraf af waar de bus stopt en hoe u bij de gangway komt. Bij een beperkte toegang helpt de chauffeur met de bagage.',
    faqs: [
      { q: 'Kan ik naar de cruiseterminal gebracht worden?', a: 'Ja, we brengen u tot bij de terminal, met ruimte voor bagage naast de rolstoel.' },
      { q: 'Kan ik na de cruise direct doorreizen?', a: 'Ja, bijvoorbeeld naar Schiphol of naar huis. Plan de rit vooraf in.' },
      { q: 'Halen jullie ook in IJmuiden zelf op?', a: 'Ja, inwoners van IJmuiden halen we op voor afspraken en familiebezoek.' },
      { q: 'Kunnen jullie \'s nachts rijden?', a: 'Ja, we zijn 24/7 bereikbaar.' },
    ],
  },

  {
    slug: 'beverwijk',
    name: 'Beverwijk',
    region: 'Kennemerland en Noord-Holland',
    nearby: ['ijmuiden', 'haarlem', 'zaandam', 'alkmaar', 'amsterdam'],
    photo: { src: 'instappen-rolstoelbus.jpg', alt: 'Rolstoelbus met geopende achterdeuren, klaar voor instappen', pos: 'center' },
    metaDescription: 'Rolstoeltaxi Beverwijk: rolstoelvervoer in Beverwijk en Wijk aan Zee, naar de Bazaar, het strand en Haarlem. Elektrische laadklep, 24/7 spoedservice. Bel direct.',
    lead: 'Beverwijk staat bekend om de Bazaar, maar ook om Wijk aan Zee, een strand en een sterke regio-identiteit. Voor een rolstoelrit betekent dat: veel bezoekers, veel drukte, weinig parkeerruimte.',
    intro: [
      'In Beverwijk is een rit naar de Bazaar in het weekend een avontuur op zich. Er is veel bezoek, en voor iemand in een rolstoel is een afgelegen parkeerplaats niet praktisch. Wij spreken vooraf af waar we u afzetten, zodat u zo dicht mogelijk bij de ingang bent.',
      'Ook Wijk aan Zee, met het strand en het schaaktoernooi, valt onder Beverwijk. Wij rijden er naartoe en terug, en helpen op drukke dagen bij het vinden van een goede plek.',
    ],
    plekken: [
      { t: 'Beverwijkse Bazaar', d: 'Een van de grootste overdekte markten van Nederland. We zetten u af bij een toegankelijke ingang.' },
      { t: 'Station Beverwijk', d: 'Aansluiting op de trein richting Haarlem en Alkmaar. Wij regelen het laatste stuk.' },
      { t: 'Wijk aan Zee', d: 'Het strand en het dorp, ook bekend van het jaarlijkse schaaktoernooi.' },
      { t: 'Breestraat en het centrum', d: 'De winkelstraat van Beverwijk. We spreken een afzetplek af.' },
      { t: 'Duinen en kust bij Wijk aan Zee', d: 'Voor een wandeling of dagje uit, met scootmobiel of rolstoel.' },
      { t: 'Wijken en zorgcomplexen', d: 'We halen u op bij de deur en helpen over drempels.' },
    ],
    ritten: [
      { t: 'Beverwijk naar Haarlem', d: 'Voor afspraken, zorg of familiebezoek in Haarlem.' },
      { t: 'Beverwijk naar Amsterdam', d: 'Een dagje de stad in of een afspraak.' },
      { t: 'Beverwijk naar Alkmaar', d: 'Naar het noorden, bijvoorbeeld voor familie of zorg.' },
      { t: 'Beverwijk naar IJmuiden', d: 'Voor de zeehaven of het strand.' },
      { t: 'Binnen Beverwijk en Wijk aan Zee', d: 'Van huis naar dagbesteding of de huisarts.' },
    ],
    spoed: 'In Beverwijk komt een spoedrit vaak voort uit een ontslag of een plotselinge afspraak. Bel de spoedlijn met uw adres en bestemming, dan noemen we bij het eerste telefoontje de aankomsttijd en de prijs.',
    bereik: 'Op marktdagen en in het weekend is het rond de Bazaar druk. We bespreken vooraf waar u wordt afgezet en op welk tijdstip we u weer ophalen. Buiten de drukte is de bus doorgaans tot voor de deur.',
    faqs: [
      { q: 'Kunnen jullie mij naar de Bazaar brengen?', a: 'Ja, heen en terug. We spreken vooraf een toegankelijke ingang en ophaaltijd af.' },
      { q: 'Rijden jullie ook naar Wijk aan Zee?', a: 'Ja, ook naar het strand en het dorp.' },
      { q: 'Kan ik een vaste rit afspreken?', a: 'Ja, bijvoorbeeld voor dagbesteding of een terugkerende behandeling.' },
      { q: 'Werken jullie ook in het weekend?', a: 'Ja, we zijn 24/7 bereikbaar.' },
    ],
  },

  {
    slug: 'zaandam',
    name: 'Zaandam',
    region: 'Kennemerland en Noord-Holland',
    nearby: ['amsterdam', 'purmerend', 'beverwijk', 'ijmuiden', 'alkmaar'],
    photo: { src: 'rolstoelbus-baksteen-laadklep.jpg', alt: 'Rolstoelbus met laadklep voor een gebouw van rode baksteen', pos: 'center' },
    metaDescription: 'Rolstoeltaxi Zaandam: rolstoelvervoer in Zaanstad, naar de Zaanse Schans, Amsterdam en Schiphol. Elektrische laadklep, 24/7 spoedservice. Bel direct.',
    lead: 'Zaandam is de hoofdplaats van Zaanstad, aan de Zaan, met bekende bezienswaardigheden en veel bedrijvigheid. Voor een rolstoelrit betekent dat: veel ritten naar zorg, werk en uitjes.',
    intro: [
      'Zaanstad is een verzameling van oude Zaanse dorpen aan het water, met Zaandam als grootste kern. De Zaanse Schans trekt veel bezoekers, en het Zaans Museum en het Czaar Peterhuisje laten zien waarom de streek beroemd is.',
      'Voor inwoners in een rolstoel is het minder een museum en meer een dagelijkse stad: naar de huisarts, dagbesteding of familie. Wij rijden u er, en ook naar Amsterdam en Schiphol.',
    ],
    plekken: [
      { t: 'Zaanse Schans', d: 'De bekende molens en houten huizen. We zetten u af bij een toegankelijke ingang.' },
      { t: 'Station Zaandam', d: 'Aansluiting op de trein richting Amsterdam. Wij regelen het laatste stuk.' },
      { t: 'Gedempte Gracht en het centrum', d: 'Winkels en horeca in het hart van Zaandam. We spreken een afzetplek af.' },
      { t: 'Zaans Museum en Czaar Peterhuisje', d: 'Twee culturele plekken in de buurt. We regelen heen en terug.' },
      { t: 'Inntel Hotels Amsterdam-Zaandam', d: 'Het opvallende hotel aan de Zaan. Voor overnachtingen en evenementen halen we u op.' },
      { t: 'Wijken in Zaanstad', d: 'Ook Zaandijk, Koog aan de Zaan en Krommenie bedienen we.' },
    ],
    ritten: [
      { t: 'Zaandam naar Amsterdam', d: 'Voor afspraken, familiebezoek of een dagje stad.' },
      { t: 'Zaandam naar Schiphol', d: 'Voor vluchten vanaf Schiphol, met bagage.' },
      { t: 'Zaandam naar Purmerend', d: 'Naar de andere kant van de regio.' },
      { t: 'Zaandam naar Haarlem', d: 'Voor zorg of familie in Haarlem.' },
      { t: 'Binnen Zaanstad', d: 'Van huis naar dagbesteding of de huisarts.' },
    ],
    spoed: 'In Zaandam kan spoed nodig zijn bij een ontslag of een onverwachte afspraak. Bel de spoedlijn met uw adres en bestemming, dan noemen we de aankomsttijd en de prijs.',
    bereik: 'Zaandam heeft veel water en bruggen. Onze chauffeurs kennen de routes en kiezen de juiste doorgang. Bij een adres aan een smalle weg spreken we vooraf een ophaalpunt af.',
    faqs: [
      { q: 'Kunnen jullie mij naar de Zaanse Schans brengen?', a: 'Ja, we zetten u af bij een toegankelijke ingang en spreken een ophaaltijd af.' },
      { q: 'Rijden jullie ook in Zaandijk en Koog aan de Zaan?', a: 'Ja, alle kernen van Zaanstad.' },
      { q: 'Kan ik naar Schiphol gebracht worden?', a: 'Ja, geef uw vluchtgegevens door, dan rekenen we terug vanaf de incheckdeadline.' },
      { q: 'Kan ik een vaste rit afspreken?', a: 'Ja, bijvoorbeeld voor dagbesteding.' },
    ],
  },

  {
    slug: 'purmerend',
    name: 'Purmerend',
    region: 'Kennemerland en Noord-Holland',
    nearby: ['zaandam', 'amsterdam', 'alkmaar', 'beverwijk', 'diemen'],
    photo: { src: 'rolstoelbus-laadklep-hoogbouw.jpg', alt: 'Rolstoelbus met uitgeklapte laadklep', pos: 'center' },
    metaDescription: 'Rolstoeltaxi Purmerend: rolstoelvervoer in Purmerend en Waterland, naar Amsterdam, Zaandam en Schiphol. Elektrische laadklep, 24/7 spoedservice. Bel direct.',
    lead: 'Purmerend ligt in Waterland, een polderlandschap met dijken, sloten en veel ruimte. Openbaar vervoer is er goed, maar niet altijd praktisch als u een rolstoel heeft.',
    intro: [
      'Purmerend is een van de grootste plaatsen in de regio, met een centrum aan de Koemarkt en grote woonwijken zoals Weidevenne. Daaromheen liggen de polders, waar de wegen smal zijn en de afstanden groot.',
      'Wij halen u op in Purmerend en de omliggende dorpen, en brengen u naar Amsterdam, Zaandam of Schiphol. Voor spoed belt u direct, voor vaste ritten plannen we een schema.',
    ],
    plekken: [
      { t: 'Koemarkt en het centrum', d: 'Winkels, horeca en het stadhuis. We spreken een toegankelijke afzetplek af.' },
      { t: 'Busstation Purmerend', d: 'Het knooppunt voor de bus richting Amsterdam en Zaandam. Wij regelen de rit als de bus niet lukt.' },
      { t: 'Weidevenne', d: 'Een grote nieuwbouwwijk met veel appartementen. De chauffeur helpt tot in de lift.' },
      { t: 'De Beemster', d: 'Het UNESCO-polderlandschap ten noorden van Purmerend, voor een dagje uit.' },
      { t: 'Overwhere en Gors', d: 'Twee wijken aan de oostkant, waar we regelmatig ophalen.' },
      { t: 'Waterlandse dorpen', d: 'Ook Broek in Waterland en Monnickendam vallen in ons werkgebied.' },
    ],
    ritten: [
      { t: 'Purmerend naar Amsterdam', d: 'Voor afspraken, zorg of familiebezoek.' },
      { t: 'Purmerend naar Zaandam', d: 'Van oost naar west, door Waterland.' },
      { t: 'Purmerend naar Schiphol', d: 'Rechtstreeks naar de luchthaven.' },
      { t: 'Purmerend naar Alkmaar', d: 'Naar het noorden, voor familie of zorg.' },
      { t: 'Binnen Purmerend', d: 'Van huis naar dagbesteding of de huisarts.' },
    ],
    spoed: 'In Purmerend kan spoed nodig zijn bij een ontslag of onverwachte afspraak. Bel de spoedlijn met uw adres en bestemming, dan noemen we de aankomsttijd en de prijs.',
    bereik: 'In Purmerend zelf zijn de wegen breed. In de polders zijn ze smal en soms ongeschikt voor een grote bus; dan spreken we vooraf een ophaalpunt af.',
    faqs: [
      { q: 'Rijden jullie ook in Waterland?', a: 'Ja, ook in Broek in Waterland, Monnickendam en de omliggende dorpen.' },
      { q: 'Kunnen jullie mij naar Amsterdam brengen?', a: 'Ja, dat is een veelgevraagde rit voor afspraken en familiebezoek.' },
      { q: 'Is een vaste rit mogelijk?', a: 'Ja, bijvoorbeeld voor dagbesteding of een terugkerende behandeling.' },
      { q: 'Werken jullie ook in het weekend?', a: 'Ja, we zijn 24/7 bereikbaar.' },
    ],
  },

  {
    slug: 'alkmaar',
    name: 'Alkmaar',
    region: 'Kennemerland en Noord-Holland',
    nearby: ['beverwijk', 'purmerend', 'zaandam', 'haarlem', 'amsterdam'],
    photo: { src: 'scootmobiel-laadklep.jpg', alt: 'Scootmobiel op de laadklep van de rolstoelbus voor een gebouw', pos: 'center' },
    metaDescription: 'Rolstoeltaxi Alkmaar: rolstoelvervoer naar de kaasmarkt, het centrum en de zorg, vanuit Noord-Holland. Elektrische laadklep, 24/7 spoedservice. Bel direct.',
    lead: 'Alkmaar is de stad van de kaasmarkt, de grachten en het Waagplein. Voor een rolstoelrit betekent dat: veel toerisme op vaste momenten, en een rustige stad daarbuiten.',
    intro: [
      'De kaasmarkt trekt in het seizoen op vrijdagochtend veel bezoekers naar het Waagplein. Voor iemand in een rolstoel is dat een prachtig gezicht, maar ook een drukke plek om te bereiken. Wij spreken vooraf af waar u wordt afgezet en op welk tijdstip we u weer ophalen.',
      'Daarbuiten is Alkmaar een rustige stad met een historisch centrum, grachten en een station. Wij rijden u van en naar afspraken, zorg of familie, in Alkmaar en de omgeving.',
    ],
    plekken: [
      { t: 'Waagplein en de kaasmarkt', d: 'Het bekendste plein van Alkmaar. Op marktdagen plannen we vooraf een afzetplek.' },
      { t: 'Grote of Sint-Laurenskerk', d: 'Het grote monument in het centrum. We zetten u af bij de toegankelijke ingang.' },
      { t: 'Station Alkmaar', d: 'Aansluiting op de trein. Wij regelen het laatste stuk.' },
      { t: 'Verdronkenoord en de grachten', d: 'Rustige straten langs het water, voor een wandeling of dagje uit.' },
      { t: 'Victoriepark en Alkmaarderhout', d: 'Groene plekken vlak bij het centrum.' },
      { t: 'Wijken en zorgcomplexen', d: 'We halen u op bij de deur, en helpen over drempels.' },
    ],
    ritten: [
      { t: 'Alkmaar naar Amsterdam', d: 'Voor afspraken, familiebezoek of een dagje stad.' },
      { t: 'Alkmaar naar Schiphol', d: 'Voor vluchten, met bagage.' },
      { t: 'Alkmaar naar Haarlem', d: 'Naar het zuiden, voor zorg of familie.' },
      { t: 'Alkmaar naar Purmerend', d: 'Door Noord-Holland, naar de andere kant van de regio.' },
      { t: 'Binnen Alkmaar', d: 'Van huis naar dagbesteding of de huisarts.' },
    ],
    spoed: 'In Alkmaar kan spoed nodig zijn bij een ontslag of een onverwachte afspraak. Bel de spoedlijn met uw adres en bestemming, dan noemen we de aankomsttijd en de prijs.',
    bereik: 'Het centrum van Alkmaar is deels autoluw en heeft grachten. Wij spreken vooraf af waar u wordt opgehaald. Buiten het centrum is het eenvoudiger: daar rijdt de bus doorgaans tot voor de deur.',
    faqs: [
      { q: 'Kunnen jullie mij naar de kaasmarkt brengen?', a: 'Ja, heen en terug. Op marktdagen spreken we vooraf een afzetplek en ophaaltijd af.' },
      { q: 'Kan ik een scootmobiel meenemen?', a: 'Ja, de laadklep is geschikt voor scootmobielen. Geef het model door bij het boeken.' },
      { q: 'Kunnen jullie mij naar Schiphol brengen?', a: 'Ja, geef uw vluchtgegevens door, dan rekenen we terug vanaf de incheckdeadline.' },
      { q: 'Kan ik een vaste rit afspreken?', a: 'Ja, bijvoorbeeld voor dagbesteding of een terugkerende behandeling.' },
    ],
  },
];
