module.exports = [
  {
    slug: 'haarlem',
    name: 'Haarlem',
    region: 'Kennemerland en Noord-Holland',
    nearby: ['heemstede', 'zandvoort', 'amsterdam', 'ijmuiden', 'beverwijk'],
    photo: { src: 'haarlem-grote-markt.jpg', alt: 'Rolstoelbus met uitgeklapte laadklep op de Grote Markt in Haarlem, naast het standbeeld van Laurens Janszoon Coster', pos: 'center 58%' },
    portrait: true,
    metaDescription: 'Rolstoeltaxi Haarlem met spoedservice: rolstoelvervoer in de binnenstad, naar Amsterdam, Schiphol en de kust. Elektrische laadklep, 24/7 bereikbaar. Bel direct.',
    lead: 'Haarlem heeft een prachtige binnenstad vol kasseien, grachten en smalle straten. Voor een rolstoelrit is dat een uitdaging die wij kennen, van de Grote Markt tot de Spaarne.',
    intro: [
      'De Grote Markt met het standbeeld van Laurens Janszoon Coster, de Sint-Bavokerk en het Stadhuis: dit is het hart van Haarlem, en het is ook de plek waar onze bus regelmatig staat. Op de foto op deze pagina ziet u hem met uitgeklapte laadklep op het plein, precies zoals we werken.',
      'Een rit in Haarlem begint bij het vinden van de juiste plek. In de binnenstad zijn straten autoluw, sommige bruggen laag en de kasseien onprettig voor een rolstoel. Wij spreken vooraf af waar we u ophalen, zodat u zo min mogelijk over de stenen hoeft.',
    ],
    plekken: [
      { t: 'Grote Markt en Sint-Bavokerk', d: 'Het plein in het centrum. We zetten u zo dicht mogelijk bij het gewenste terras, de kerk of het museum af.' },
      { t: 'Frans Hals Museum en Teylers Museum', d: 'Twee bekende musea, beide goed bereikbaar. We regelen heen en terug in één keer.' },
      { t: 'Station Haarlem', d: 'Aansluiting op de trein. Wij helpen bij de aansluiting als het openbaar vervoer niet lukt.' },
      { t: 'Spaarne en de Bakenessergracht', d: 'Rustige wandelroutes langs het water. Voor een dagje uit halen we u op en brengen we u terug.' },
      { t: 'Haarlemmerhout en Kenaupark', d: 'Twee groene plekken vlak bij het centrum, voor een wandeling met een scootmobiel of rolstoel.' },
      { t: 'Haarlem-Noord en Schalkwijk', d: 'Grote woonwijken met veel senioren. We halen u op aan de deur en helpen over drempels.' },
    ],
    ritten: [
      { t: 'Haarlem naar Amsterdam', d: 'Voor afspraken, familiebezoek of een dagje stad.' },
      { t: 'Haarlem naar Schiphol', d: 'Vroege vluchten zijn geen probleem: we zijn dag en nacht bereikbaar.' },
      { t: 'Haarlem naar Zandvoort', d: 'Een dagje naar het strand, met scootmobiel of rolstoel.' },
      { t: 'Haarlem naar Heemstede', d: 'Een korte rit voor de winkels aan de Binnenweg of familie.' },
      { t: 'Binnen Haarlem', d: 'Van huis naar dagbesteding, de huisarts of een afspraak in een andere wijk.' },
    ],
    spoed: 'In Haarlem komt spoed vaak voort uit een situatie thuis of in een zorginstelling: een val, een ontslag of een afspraak die naar voren is gehaald. Bel de spoedlijn met uw adres en bestemming, dan noemen we bij het eerste telefoontje de aankomsttijd en de prijs.',
    bereik: 'De binnenstad is deels autoluw en heeft veel kasseien. Buiten het centrum is het eenvoudiger: daar rijdt de bus doorgaans tot voor de deur. We bespreken vooraf waar u wordt opgehaald, zodat de laadklep veilig kan worden uitgeklapt.',
    faqs: [
      { q: 'Kan de bus in de Haarlemse binnenstad komen?', a: 'Tot vlak bij de bestemming meestal wel. In autoluwe straten spreken we vooraf een ophaalpunt af waar de laadklep veilig kan worden uitgeklapt.' },
      { q: 'Rijden jullie ook naar het strand van Zandvoort?', a: 'Ja, voor een dagje uit halen we u op en brengen u terug op een afgesproken tijd.' },
      { q: 'Kan ik vanuit Haarlem naar Schiphol worden gebracht?', a: 'Ja, ook voor vroege vluchten. Geef uw vluchtgegevens door, dan rekenen we terug vanaf de incheckdeadline.' },
      { q: 'Kan ik een vaste rit afspreken?', a: 'Ja, bijvoorbeeld voor dagbesteding of een terugkerende behandeling.' },
    ],
    en: {
      metaDescription: 'Rolstoeltaxi Haarlem with emergency service: wheelchair transport in the city centre, to Amsterdam, Schiphol and the coast. Electric ramp, 24/7 available. Call now.',
      lead: "Haarlem has a beautiful city centre full of cobblestones, canals and narrow streets. For a wheelchair ride that's a challenge we know well, from the Grote Markt to the Spaarne.",
      intro: [
        "The Grote Markt with the statue of Laurens Janszoon Coster, the Sint-Bavokerk and the town hall: this is the heart of Haarlem, and it's also a spot where our vehicle regularly stands. In the photo on this page you can see it with the ramp deployed on the square, exactly how we work.",
        "A ride in Haarlem starts with finding the right spot. In the city centre, streets are car-free, some bridges are low, and the cobblestones are unpleasant for a wheelchair. We agree beforehand where we'll pick you up, so you have to cross as few cobblestones as possible.",
      ],
      plekken: [
        { t: 'Grote Markt and Sint-Bavokerk', d: 'The square in the centre. We drop you off as close as possible to the terrace, church or museum you want.' },
        { t: 'Frans Hals Museum and Teylers Museum', d: 'Two well-known museums, both easily accessible. We arrange the outbound and return trip in one go.' },
        { t: 'Haarlem station', d: 'Connects to the train. We help with the connection when public transport is not an option.' },
        { t: 'The Spaarne and Bakenessergracht', d: 'Quiet walking routes along the water. For a day out we pick you up and bring you back.' },
        { t: 'Haarlemmerhout and Kenaupark', d: 'Two green spots close to the centre, for a walk with a mobility scooter or wheelchair.' },
        { t: 'Haarlem-Noord and Schalkwijk', d: 'Large residential areas with many seniors. We pick you up at the door and help over thresholds.' },
      ],
      ritten: [
        { t: 'Haarlem to Amsterdam', d: 'For appointments, family visits or a day in the city.' },
        { t: 'Haarlem to Schiphol', d: 'Early flights are no problem: we are reachable day and night.' },
        { t: 'Haarlem to Zandvoort', d: 'A day at the beach, with a mobility scooter or wheelchair.' },
        { t: 'Haarlem to Heemstede', d: 'A short ride for the shops on the Binnenweg or family.' },
        { t: 'Within Haarlem', d: 'From home to day care, the GP or an appointment in another neighbourhood.' },
      ],
      spoed: "In Haarlem, emergencies often stem from a situation at home or in a care facility: a fall, a discharge, or an appointment that's been moved up. Call the emergency line with your address and destination, and we'll give you the arrival time and price on the first phone call.",
      bereik: "The city centre is partly car-free and has many cobblestones. Outside the centre it's easier: the vehicle usually drives right up to the door. We discuss beforehand where you'll be picked up, so the ramp can be safely deployed.",
      faqs: [
        { q: 'Can the vehicle come into the Haarlem city centre?', a: 'Usually right up to near the destination. On car-free streets we agree on a pickup point beforehand where the ramp can be safely deployed.' },
        { q: 'Do you also drive to the beach at Zandvoort?', a: 'Yes, for a day out we pick you up and bring you back at an agreed time.' },
        { q: 'Can I be taken from Haarlem to Schiphol?', a: "Yes, for early flights too. Let us know your flight details, and we'll calculate backwards from the check-in deadline." },
        { q: 'Can I arrange a regular ride?', a: 'Yes, for example for day care or a recurring treatment.' },
      ],
    },
  },

  {
    slug: 'heemstede',
    name: 'Heemstede',
    region: 'Kennemerland en Noord-Holland',
    nearby: ['haarlem', 'zandvoort', 'hoofddorp', 'amsterdam', 'leiden'],
    photo: { src: 'rolstoelbus-zorginstelling.jpg', alt: 'Rolstoelbus voor een woon- en zorggebouw', pos: 'center' },
    metaDescription: 'Rolstoeltaxi Heemstede: rolstoelvervoer in Heemstede en Aerdenhout, naar Haarlem, Amsterdam en Schiphol. Elektrische laadklep, 24/7 spoedservice. Bel direct.',
    lead: 'Heemstede ligt naast Haarlem, met veel groen en een sterke gemeenschap van senioren. Voor een rolstoelrit betekent dat: veel ritten naar zorg, winkels en familie.',
    intro: [
      'Heemstede is een rustige, groene plaats. Veel inwoners zijn ouder en wonen zelfstandig of in een zorgcomplex. Voor hen is een betrouwbare rit naar de huisarts, de kapper of familie geen luxe maar een dagelijkse noodzaak.',
      'Rolstoeltaxi Spoed rijdt in Heemstede en Aerdenhout, en naar Haarlem, Amsterdam en Schiphol. Voor spoed belt u direct, voor vaste ritten maken we een schema.',
    ],
    plekken: [
      { t: 'Binnenweg', d: 'De winkelstraat van Heemstede. We zetten u af waar u zo dicht mogelijk bij uw bestemming bent.' },
      { t: 'Station Heemstede-Aerdenhout', d: 'Aansluiting op de trein richting Haarlem en Leiden. Wij regelen het laatste stuk.' },
      { t: 'Groenendaal', d: 'Een groot park aan de rand van Heemstede, voor een wandeling met scootmobiel of rolstoel.' },
      { t: 'Heemsteedse Dreef', d: 'Een van de mooiste lanen van de regio. Voor een dagje uit halen we u op.' },
      { t: 'Woon- en zorgcomplexen', d: 'Veel inwoners wonen in een complex. De chauffeur helpt tot in de gang.' },
      { t: 'Aerdenhout', d: 'Het dorp ten noorden van Heemstede, dat we ook bedienen.' },
    ],
    ritten: [
      { t: 'Heemstede naar Haarlem', d: 'Naar het centrum of een afspraak in het ziekenhuis in Haarlem.' },
      { t: 'Heemstede naar Amsterdam', d: 'Voor familiebezoek, een museum of een afspraak.' },
      { t: 'Heemstede naar Schiphol', d: 'Rechtstreeks naar de vertrekhal.' },
      { t: 'Heemstede naar Zandvoort', d: 'Een dagje naar het strand.' },
      { t: 'Binnen Heemstede', d: 'Van huis naar dagbesteding, de huisarts of de kapper.' },
    ],
    spoed: 'Omdat Heemstede dicht bij Haarlem ligt, kunnen onze bussen doorgaans snel bij u zijn. Bel de spoedlijn met uw adres en bestemming, dan noemen we de aankomsttijd en de prijs.',
    bereik: 'De straten in Heemstede zijn ruim en de meeste adressen zijn goed bereikbaar. Bij een zorgcomplex met een eigen ingang of oprit spreken we af waar de bus het beste kan stoppen.',
    faqs: [
      { q: 'Rijden jullie ook in Aerdenhout?', a: 'Ja, Aerdenhout valt binnen ons werkgebied.' },
      { q: 'Kunnen jullie mij bij een zorgcomplex ophalen?', a: 'Ja, de chauffeur helpt tot in de gang of lift. Geef bij het boeken aan hoe de toegang is.' },
      { q: 'Kan ik een wekelijkse rit naar dagbesteding afspreken?', a: 'Ja, we plannen terugkerende ritten graag in.' },
      { q: 'Rijden jullie ook in het weekend?', a: 'Ja, we zijn 24/7 bereikbaar.' },
    ],
    en: {
      metaDescription: 'Rolstoeltaxi Heemstede: wheelchair transport in Heemstede and Aerdenhout, to Haarlem, Amsterdam and Schiphol. Electric ramp, 24/7 emergency service. Call now.',
      lead: 'Heemstede lies next to Haarlem, with plenty of greenery and a strong community of seniors. For a wheelchair ride that means: many rides to care, shops and family.',
      intro: [
        "Heemstede is a quiet, green town. Many residents are older and live independently or in a care complex. For them, a reliable ride to the GP, the hairdresser or family isn't a luxury but a daily necessity.",
        'Rolstoeltaxi Spoed drives in Heemstede and Aerdenhout, and to Haarlem, Amsterdam and Schiphol. For an emergency you call directly, for regular rides we set up a schedule.',
      ],
      plekken: [
        { t: "Binnenweg", d: "Heemstede's shopping street. We drop you off as close as possible to your destination." },
        { t: 'Heemstede-Aerdenhout station', d: 'Connects to the train towards Haarlem and Leiden. We arrange the last stretch.' },
        { t: 'Groenendaal', d: 'A large park on the edge of Heemstede, for a walk with a mobility scooter or wheelchair.' },
        { t: 'Heemsteedse Dreef', d: 'One of the most beautiful avenues in the region. For a day out we pick you up.' },
        { t: 'Residential and care complexes', d: 'Many residents live in a complex. The driver helps as far as the hallway.' },
        { t: 'Aerdenhout', d: 'The village north of Heemstede, which we also serve.' },
      ],
      ritten: [
        { t: 'Heemstede to Haarlem', d: 'To the centre or an appointment at the hospital in Haarlem.' },
        { t: 'Heemstede to Amsterdam', d: 'For a family visit, a museum or an appointment.' },
        { t: 'Heemstede to Schiphol', d: 'Straight to the departure hall.' },
        { t: 'Heemstede to Zandvoort', d: 'A day at the beach.' },
        { t: 'Within Heemstede', d: 'From home to day care, the GP or the hairdresser.' },
      ],
      spoed: "Because Heemstede is close to Haarlem, our vehicles can usually reach you quickly. Call the emergency line with your address and destination, and we'll give you the arrival time and price.",
      bereik: 'The streets in Heemstede are spacious and most addresses are easily accessible. At a care complex with its own entrance or driveway, we agree on the best place for the vehicle to stop.',
      faqs: [
        { q: 'Do you also drive in Aerdenhout?', a: 'Yes, Aerdenhout is within our service area.' },
        { q: 'Can you pick me up at a care complex?', a: 'Yes, the driver helps as far as the hallway or lift. Let us know the access details when booking.' },
        { q: 'Can I arrange a weekly ride to day care?', a: "Yes, we're happy to schedule recurring rides." },
        { q: 'Do you also drive on weekends?', a: 'Yes, we are reachable 24/7.' },
      ],
    },
  },

  {
    slug: 'zandvoort',
    name: 'Zandvoort',
    region: 'Kennemerland en Noord-Holland',
    nearby: ['haarlem', 'heemstede', 'ijmuiden', 'amsterdam', 'hoofddorp'],
    photo: { src: 'rolstoelbus-voorkant.jpg', alt: 'Rolstoelbus in de zon voor een gebouw', pos: 'center 55%' },
    metaDescription: 'Rolstoeltaxi Zandvoort: rolstoelvervoer naar het strand, het circuit en de kern, vanuit Haarlem en Amsterdam. Elektrische laadklep, 24/7 bereikbaar. Bel direct.',
    lead: 'Zandvoort is strand, circuit en een kust die veel bezoekers trekt. Voor een rolstoel is het aanpassen aan drukte en afgesloten wegen: precies waarvoor u ons belt.',
    intro: [
      'Zandvoort heeft een breed strand, een boulevard en een dorpskern die op zomerse dagen vol loopt. Ook rond raceweekenden op het circuit zijn straten afgesloten en is het openbaar vervoer overbelast. Voor iemand in een rolstoel is dat de dag waarop je niet wilt gokken.',
      'Wij zoeken vooraf uit waar u het beste kunt uitstappen en op welk tijdstip we u ophalen. Op drukke dagen bespreken we ruim van tevoren de mogelijkheden.',
    ],
    plekken: [
      { t: 'Strand en boulevard', d: 'Een dagje aan zee. We zetten u af bij een toegankelijke strandopgang en spreken een ophaaltijd af.' },
      { t: 'Circuit Zandvoort', d: 'Voor de racedagen. Straten zijn dan afgesloten, dus vooraf plannen is nodig.' },
      { t: 'Station Zandvoort aan Zee', d: 'Het eindpunt van de trein vanaf Haarlem. Wij regelen het stuk naar uw bestemming.' },
      { t: 'Gasthuisplein en de kern', d: 'Winkels en terrassen in het dorp. We spreken een toegankelijke afzetplek af.' },
      { t: 'Nationaal Park Zuid-Kennemerland', d: 'Duinen en wandelpaden, voor wie een rustig dagje uit wil.' },
      { t: 'Woonwijken en zorgcomplexen', d: 'Ook inwoners halen we op, voor afspraken en familiebezoek.' },
    ],
    ritten: [
      { t: 'Zandvoort naar Haarlem', d: 'Voor afspraken en zorg in de binnenstad.' },
      { t: 'Zandvoort naar Amsterdam', d: 'Een dagje de stad in, of terug naar huis.' },
      { t: 'Zandvoort naar Schiphol', d: 'Voor vluchten vanaf Schiphol, met bagage.' },
      { t: 'Amsterdam naar Zandvoort', d: 'Een dagje naar het strand, met rolstoel of scootmobiel.' },
      { t: 'Binnen Zandvoort', d: 'Korte ritten voor inwoners, bijvoorbeeld naar de huisarts.' },
    ],
    spoed: 'Ook in Zandvoort kan spoed nodig zijn, bijvoorbeeld bij een ontslag of een plotselinge afspraak. Bel de spoedlijn, dan noemen we de aankomsttijd en de prijs. Op drukke dagen kunnen straten afgesloten zijn en houden we daar rekening mee.',
    bereik: 'Op een zonnige dag of tijdens een evenement is Zandvoort moeilijk bereikbaar. Wij plannen dan een vaste afzetplek en ophaaltijd, zodat u niet hoeft te improviseren.',
    faqs: [
      { q: 'Kan ik met een scootmobiel naar het strand?', a: 'Ja, we zetten u af bij een toegankelijke opgang. Voor het strand zelf heeft u eventueel een aangepaste strandrolstoel nodig; vraag dat na bij de strandpaviljoens.' },
      { q: 'Wat als er een evenement op het circuit is?', a: 'Plan dan ruim van tevoren. Straten zijn afgesloten en we spreken een vaste afzetplek en ophaaltijd af.' },
      { q: 'Rijden jullie ook \'s avonds terug?', a: 'Ja, we zijn 24/7 bereikbaar. We plannen de terugrit vooraf in.' },
      { q: 'Kunnen jullie mij vanuit Amsterdam naar Zandvoort brengen?', a: 'Ja, dat is een veelgevraagde rit voor een dagje uit.' },
    ],
    en: {
      metaDescription: 'Rolstoeltaxi Zandvoort: wheelchair transport to the beach, the circuit and the village centre, from Haarlem and Amsterdam. Electric ramp, 24/7 available. Call now.',
      lead: 'Zandvoort means beach, circuit and a coastline that attracts many visitors. For a wheelchair, that means adapting to crowds and closed roads: exactly what you call us for.',
      intro: [
        "Zandvoort has a wide beach, a boulevard, and a village centre that gets crowded on summer days. Around race weekends at the circuit, streets are also closed and public transport is overloaded. For someone in a wheelchair, that's a day you don't want to leave to chance.",
        "We find out beforehand where's best for you to get out and what time we'll pick you up. On busy days we discuss the options well in advance.",
      ],
      plekken: [
        { t: 'Beach and boulevard', d: 'A day by the sea. We drop you off at an accessible beach access point and agree on a pickup time.' },
        { t: 'Circuit Zandvoort', d: 'For race days. Streets are closed then, so planning ahead is needed.' },
        { t: 'Zandvoort aan Zee station', d: 'The end of the train line from Haarlem. We arrange the stretch to your destination.' },
        { t: 'Gasthuisplein and the village centre', d: 'Shops and terraces in the village. We agree on an accessible drop-off spot.' },
        { t: 'Zuid-Kennemerland National Park', d: 'Dunes and walking trails, for anyone who wants a quiet day out.' },
        { t: 'Residential areas and care complexes', d: 'We also pick up residents, for appointments and family visits.' },
      ],
      ritten: [
        { t: 'Zandvoort to Haarlem', d: 'For appointments and care in the city centre.' },
        { t: 'Zandvoort to Amsterdam', d: 'A day in the city, or back home.' },
        { t: 'Zandvoort to Schiphol', d: 'For flights from Schiphol, with luggage.' },
        { t: 'Amsterdam to Zandvoort', d: 'A day at the beach, with a wheelchair or mobility scooter.' },
        { t: 'Within Zandvoort', d: 'Short rides for residents, for example to the GP.' },
      ],
      spoed: "Emergencies can happen in Zandvoort too, for example with a discharge or a sudden appointment. Call the emergency line, and we'll give you the arrival time and price. On busy days, streets may be closed and we take that into account.",
      bereik: "On a sunny day or during an event, Zandvoort is hard to reach. We then plan a fixed drop-off spot and pickup time, so you don't have to improvise.",
      faqs: [
        { q: 'Can I go to the beach with a mobility scooter?', a: 'Yes, we drop you off at an accessible access point. For the beach itself you may need an adapted beach wheelchair; ask about that at the beach pavilions.' },
        { q: 'What if there is an event at the circuit?', a: 'Plan well in advance. Streets are closed and we agree on a fixed drop-off spot and pickup time.' },
        { q: 'Do you also drive back in the evening?', a: 'Yes, we are reachable 24/7. We schedule the return ride in advance.' },
        { q: 'Can you take me from Amsterdam to Zandvoort?', a: 'Yes, that is a frequently requested ride for a day out.' },
      ],
    },
  },

  {
    slug: 'ijmuiden',
    name: 'IJmuiden',
    region: 'Kennemerland en Noord-Holland',
    nearby: ['beverwijk', 'haarlem', 'zandvoort', 'amsterdam', 'zaandam'],
    photo: { src: 'luchthavenvervoer-bagage.jpg', alt: 'Rolstoelbus met laadklep op een kade bij een groot schip, reizigers met bagage op de achtergrond', pos: 'center' },
    metaDescription: 'Rolstoeltaxi IJmuiden: rolstoelvervoer naar de zeehaven, de cruiseterminal en het strand, vanuit Amsterdam en Haarlem. Bagage, laadklep, 24/7 bereikbaar.',
    lead: 'IJmuiden is een havenstad aan de Noordzee, met een cruiseterminal, een strand en veel industrie. Voor een rolstoelreiziger is het vooral een plek waar de rit naar de kade erg belangrijk is.',
    intro: [
      'De zeehaven van IJmuiden ontvangt jaarlijks cruiseschepen en veerboten. Reizigers met een rolstoel of scootmobiel moeten op een vaste tijd aan boord of van boord, en dat vraagt om een betrouwbare rit met ruimte voor bagage.',
      'Naast de haven is er het strand, het centrum en de wijk Velsen-Zuid. Ook voor inwoners rijden we: naar afspraken, familie en dagbesteding.',
    ],
    plekken: [
      { t: 'Cruiseterminal IJmuiden', d: 'Voor in- en uitschepen. We spreken een vaste tijd en plek af, met ruimte voor koffers en rolstoel.' },
      { t: 'Zeehaven en sluizen', d: 'Het industriële hart van IJmuiden. Voor werk of een bezoek rijden we u erheen.' },
      { t: 'Strand en Kennemerstrand', d: 'Een dagje aan zee vanuit Amsterdam of Haarlem.' },
      { t: 'Centrum IJmuiden', d: 'Winkels en voorzieningen. We spreken een toegankelijke afzetplek af.' },
      { t: 'Velsen-Zuid en Driehuis', d: 'Woonwijken waar we regelmatig ophalen.' },
      { t: 'Noordzeekanaal en de pier', d: 'Voor een wandeling langs het water met scootmobiel of rolstoel.' },
    ],
    ritten: [
      { t: 'Amsterdam naar IJmuiden', d: 'Voor een cruise, een dagje uit of een afspraak.' },
      { t: 'IJmuiden naar Schiphol', d: 'Voor reizigers die na een cruise doorvliegen.' },
      { t: 'IJmuiden naar Haarlem', d: 'Van kust naar stad.' },
      { t: 'IJmuiden naar Beverwijk', d: 'Een korte rit langs het kanaal, bijvoorbeeld naar familie of de winkels.' },
      { t: 'Binnen IJmuiden', d: 'Van huis naar dagbesteding of de huisarts.' },
    ],
    spoed: 'Bij een cruise of veerboot is de tijd bepalend. Een gemiste aansluiting kan de hele reis kosten. Bel de spoedlijn met de vertrektijd van het schip, dan rekenen we terug en noemen we meteen de prijs.',
    bereik: 'De haven is groot en de terminal ligt op een vaste plek. We spreken vooraf af waar de bus stopt en hoe u bij de gangway komt. Bij een beperkte toegang helpt de chauffeur met de bagage.',
    faqs: [
      { q: 'Kan ik naar de cruiseterminal gebracht worden?', a: 'Ja, we brengen u tot bij de terminal, met ruimte voor bagage naast de rolstoel.' },
      { q: 'Kan ik na de cruise direct doorreizen?', a: 'Ja, bijvoorbeeld naar Schiphol of naar huis. Plan de rit vooraf in.' },
      { q: 'Halen jullie ook in IJmuiden zelf op?', a: 'Ja, inwoners van IJmuiden halen we op voor afspraken en familiebezoek.' },
      { q: 'Kunnen jullie \'s nachts rijden?', a: 'Ja, we zijn 24/7 bereikbaar.' },
    ],
    en: {
      metaDescription: 'Rolstoeltaxi IJmuiden: wheelchair transport to the seaport, the cruise terminal and the beach, from Amsterdam and Haarlem. Luggage, ramp, 24/7 available.',
      lead: "IJmuiden is a port town on the North Sea, with a cruise terminal, a beach and a lot of industry. For a wheelchair traveller, it's mainly a place where the ride to the quay really matters.",
      intro: [
        'The seaport of IJmuiden welcomes cruise ships and ferries every year. Travellers with a wheelchair or mobility scooter need to board or disembark at a fixed time, which calls for a reliable ride with room for luggage.',
        'Besides the port there is the beach, the town centre and the Velsen-Zuid neighbourhood. We also drive for residents: to appointments, family and day care.',
      ],
      plekken: [
        { t: 'IJmuiden cruise terminal', d: 'For boarding and disembarking. We agree on a fixed time and place, with room for suitcases and a wheelchair.' },
        { t: 'Seaport and locks', d: 'The industrial heart of IJmuiden. For work or a visit we drive you there.' },
        { t: 'Beach and Kennemerstrand', d: 'A day by the sea from Amsterdam or Haarlem.' },
        { t: 'IJmuiden centre', d: 'Shops and facilities. We agree on an accessible drop-off spot.' },
        { t: 'Velsen-Zuid and Driehuis', d: 'Residential areas where we regularly pick up.' },
        { t: 'North Sea Canal and the pier', d: 'For a walk along the water with a mobility scooter or wheelchair.' },
      ],
      ritten: [
        { t: 'Amsterdam to IJmuiden', d: 'For a cruise, a day out or an appointment.' },
        { t: 'IJmuiden to Schiphol', d: 'For travellers flying onward after a cruise.' },
        { t: 'IJmuiden to Haarlem', d: 'From coast to city.' },
        { t: 'IJmuiden to Beverwijk', d: 'A short ride along the canal, for example to family or the shops.' },
        { t: 'Within IJmuiden', d: 'From home to day care or the GP.' },
      ],
      spoed: "With a cruise or ferry, timing is everything. A missed connection can cost you the whole trip. Call the emergency line with the ship's departure time, and we'll calculate backwards and name the price right away.",
      bereik: 'The port is large and the terminal is at a fixed location. We agree beforehand where the vehicle stops and how you get to the gangway. With limited access, the driver helps with the luggage.',
      faqs: [
        { q: 'Can I be taken to the cruise terminal?', a: 'Yes, we take you right to the terminal, with room for luggage next to the wheelchair.' },
        { q: 'Can I travel onward right after the cruise?', a: 'Yes, for example to Schiphol or home. Schedule the ride in advance.' },
        { q: 'Do you also pick up in IJmuiden itself?', a: 'Yes, we pick up IJmuiden residents for appointments and family visits.' },
        { q: 'Can you drive at night?', a: 'Yes, we are reachable 24/7.' },
      ],
    },
  },

  {
    slug: 'beverwijk',
    name: 'Beverwijk',
    region: 'Kennemerland en Noord-Holland',
    nearby: ['ijmuiden', 'haarlem', 'zaandam', 'alkmaar', 'amsterdam'],
    photo: { src: 'instappen-rolstoelbus.jpg', alt: 'Rolstoelbus met geopende achterdeuren, klaar voor instappen', pos: 'center' },
    metaDescription: 'Rolstoeltaxi Beverwijk: rolstoelvervoer in Beverwijk en Wijk aan Zee, naar de Bazaar, het strand en Haarlem. Elektrische laadklep, 24/7 spoedservice. Bel direct.',
    lead: 'Beverwijk staat bekend om de Bazaar, maar ook om Wijk aan Zee, een strand en een sterke regio-identiteit. Voor een rolstoelrit betekent dat: veel bezoekers, veel drukte, weinig parkeerruimte.',
    intro: [
      'In Beverwijk is een rit naar de Bazaar in het weekend een avontuur op zich. Er is veel bezoek, en voor iemand in een rolstoel is een afgelegen parkeerplaats niet praktisch. Wij spreken vooraf af waar we u afzetten, zodat u zo dicht mogelijk bij de ingang bent.',
      'Ook Wijk aan Zee, met het strand en het schaaktoernooi, valt onder Beverwijk. Wij rijden er naartoe en terug, en helpen op drukke dagen bij het vinden van een goede plek.',
    ],
    plekken: [
      { t: 'Beverwijkse Bazaar', d: 'Een van de grootste overdekte markten van Nederland. We zetten u af bij een toegankelijke ingang.' },
      { t: 'Station Beverwijk', d: 'Aansluiting op de trein richting Haarlem en Alkmaar. Wij regelen het laatste stuk.' },
      { t: 'Wijk aan Zee', d: 'Het strand en het dorp, ook bekend van het jaarlijkse schaaktoernooi.' },
      { t: 'Breestraat en het centrum', d: 'De winkelstraat van Beverwijk. We spreken een afzetplek af.' },
      { t: 'Duinen en kust bij Wijk aan Zee', d: 'Voor een wandeling of dagje uit, met scootmobiel of rolstoel.' },
      { t: 'Wijken en zorgcomplexen', d: 'We halen u op bij de deur en helpen over drempels.' },
    ],
    ritten: [
      { t: 'Beverwijk naar Haarlem', d: 'Voor afspraken, zorg of familiebezoek in Haarlem.' },
      { t: 'Beverwijk naar Amsterdam', d: 'Een dagje de stad in of een afspraak.' },
      { t: 'Beverwijk naar Alkmaar', d: 'Naar het noorden, bijvoorbeeld voor familie of zorg.' },
      { t: 'Beverwijk naar IJmuiden', d: 'Voor de zeehaven of het strand.' },
      { t: 'Binnen Beverwijk en Wijk aan Zee', d: 'Van huis naar dagbesteding of de huisarts.' },
    ],
    spoed: 'In Beverwijk komt een spoedrit vaak voort uit een ontslag of een plotselinge afspraak. Bel de spoedlijn met uw adres en bestemming, dan noemen we bij het eerste telefoontje de aankomsttijd en de prijs.',
    bereik: 'Op marktdagen en in het weekend is het rond de Bazaar druk. We bespreken vooraf waar u wordt afgezet en op welk tijdstip we u weer ophalen. Buiten de drukte is de bus doorgaans tot voor de deur.',
    faqs: [
      { q: 'Kunnen jullie mij naar de Bazaar brengen?', a: 'Ja, heen en terug. We spreken vooraf een toegankelijke ingang en ophaaltijd af.' },
      { q: 'Rijden jullie ook naar Wijk aan Zee?', a: 'Ja, ook naar het strand en het dorp.' },
      { q: 'Kan ik een vaste rit afspreken?', a: 'Ja, bijvoorbeeld voor dagbesteding of een terugkerende behandeling.' },
      { q: 'Werken jullie ook in het weekend?', a: 'Ja, we zijn 24/7 bereikbaar.' },
    ],
    en: {
      metaDescription: 'Rolstoeltaxi Beverwijk: wheelchair transport in Beverwijk and Wijk aan Zee, to the Bazaar, the beach and Haarlem. Electric ramp, 24/7 emergency service. Call now.',
      lead: 'Beverwijk is known for the Bazaar, but also for Wijk aan Zee, a beach and a strong regional identity. For a wheelchair ride that means: many visitors, lots of crowds, little parking space.',
      intro: [
        "In Beverwijk, a ride to the Bazaar on the weekend is an adventure in itself. It gets very busy, and for someone in a wheelchair a distant parking spot isn't practical. We agree beforehand where we'll drop you off, so you're as close as possible to the entrance.",
        'Wijk aan Zee, with its beach and chess tournament, also falls under Beverwijk. We drive there and back, and on busy days help you find a good spot.',
      ],
      plekken: [
        { t: 'Beverwijk Bazaar', d: 'One of the largest indoor markets in the Netherlands. We drop you off at an accessible entrance.' },
        { t: 'Beverwijk station', d: 'Connects to the train towards Haarlem and Alkmaar. We arrange the last stretch.' },
        { t: 'Wijk aan Zee', d: 'The beach and the village, also known for the annual chess tournament.' },
        { t: 'Breestraat and the centre', d: "Beverwijk's shopping street. We agree on a drop-off spot." },
        { t: 'Dunes and coast at Wijk aan Zee', d: 'For a walk or a day out, with a mobility scooter or wheelchair.' },
        { t: 'Neighbourhoods and care complexes', d: 'We pick you up at the door and help over thresholds.' },
      ],
      ritten: [
        { t: 'Beverwijk to Haarlem', d: 'For appointments, care or family visits in Haarlem.' },
        { t: 'Beverwijk to Amsterdam', d: 'A day in the city or an appointment.' },
        { t: 'Beverwijk to Alkmaar', d: 'To the north, for example for family or care.' },
        { t: 'Beverwijk to IJmuiden', d: 'For the seaport or the beach.' },
        { t: 'Within Beverwijk and Wijk aan Zee', d: 'From home to day care or the GP.' },
      ],
      spoed: "In Beverwijk, an emergency ride often stems from a discharge or a sudden appointment. Call the emergency line with your address and destination, and we'll give you the arrival time and price on the first phone call.",
      bereik: "It gets busy around the Bazaar on market days and weekends. We discuss beforehand where you'll be dropped off and what time we'll pick you up again. Outside busy periods, the vehicle usually drives right up to the door.",
      faqs: [
        { q: 'Can you take me to the Bazaar?', a: 'Yes, both ways. We agree on an accessible entrance and pickup time beforehand.' },
        { q: 'Do you also drive to Wijk aan Zee?', a: 'Yes, to the beach and the village too.' },
        { q: 'Can I arrange a regular ride?', a: 'Yes, for example for day care or a recurring treatment.' },
        { q: 'Do you also work on weekends?', a: 'Yes, we are reachable 24/7.' },
      ],
    },
  },

  {
    slug: 'zaandam',
    name: 'Zaandam',
    region: 'Kennemerland en Noord-Holland',
    nearby: ['amsterdam', 'purmerend', 'beverwijk', 'ijmuiden', 'alkmaar'],
    photo: { src: 'rolstoelbus-baksteen-laadklep.jpg', alt: 'Rolstoelbus met laadklep voor een gebouw van rode baksteen', pos: 'center' },
    metaDescription: 'Rolstoeltaxi Zaandam: rolstoelvervoer in Zaanstad, naar de Zaanse Schans, Amsterdam en Schiphol. Elektrische laadklep, 24/7 spoedservice. Bel direct.',
    lead: 'Zaandam is de hoofdplaats van Zaanstad, aan de Zaan, met bekende bezienswaardigheden en veel bedrijvigheid. Voor een rolstoelrit betekent dat: veel ritten naar zorg, werk en uitjes.',
    intro: [
      'Zaanstad is een verzameling van oude Zaanse dorpen aan het water, met Zaandam als grootste kern. De Zaanse Schans trekt veel bezoekers, en het Zaans Museum en het Czaar Peterhuisje laten zien waarom de streek beroemd is.',
      'Voor inwoners in een rolstoel is het minder een museum en meer een dagelijkse stad: naar de huisarts, dagbesteding of familie. Wij rijden u er, en ook naar Amsterdam en Schiphol.',
    ],
    plekken: [
      { t: 'Zaanse Schans', d: 'De bekende molens en houten huizen. We zetten u af bij een toegankelijke ingang.' },
      { t: 'Station Zaandam', d: 'Aansluiting op de trein richting Amsterdam. Wij regelen het laatste stuk.' },
      { t: 'Gedempte Gracht en het centrum', d: 'Winkels en horeca in het hart van Zaandam. We spreken een afzetplek af.' },
      { t: 'Zaans Museum en Czaar Peterhuisje', d: 'Twee culturele plekken in de buurt. We regelen heen en terug.' },
      { t: 'Inntel Hotels Amsterdam-Zaandam', d: 'Het opvallende hotel aan de Zaan. Voor overnachtingen en evenementen halen we u op.' },
      { t: 'Wijken in Zaanstad', d: 'Ook Zaandijk, Koog aan de Zaan en Krommenie bedienen we.' },
    ],
    ritten: [
      { t: 'Zaandam naar Amsterdam', d: 'Voor afspraken, familiebezoek of een dagje stad.' },
      { t: 'Zaandam naar Schiphol', d: 'Voor vluchten vanaf Schiphol, met bagage.' },
      { t: 'Zaandam naar Purmerend', d: 'Naar de andere kant van de regio.' },
      { t: 'Zaandam naar Haarlem', d: 'Voor zorg of familie in Haarlem.' },
      { t: 'Binnen Zaanstad', d: 'Van huis naar dagbesteding of de huisarts.' },
    ],
    spoed: 'In Zaandam kan spoed nodig zijn bij een ontslag of een onverwachte afspraak. Bel de spoedlijn met uw adres en bestemming, dan noemen we de aankomsttijd en de prijs.',
    bereik: 'Zaandam heeft veel water en bruggen. Onze chauffeurs kennen de routes en kiezen de juiste doorgang. Bij een adres aan een smalle weg spreken we vooraf een ophaalpunt af.',
    faqs: [
      { q: 'Kunnen jullie mij naar de Zaanse Schans brengen?', a: 'Ja, we zetten u af bij een toegankelijke ingang en spreken een ophaaltijd af.' },
      { q: 'Rijden jullie ook in Zaandijk en Koog aan de Zaan?', a: 'Ja, alle kernen van Zaanstad.' },
      { q: 'Kan ik naar Schiphol gebracht worden?', a: 'Ja, geef uw vluchtgegevens door, dan rekenen we terug vanaf de incheckdeadline.' },
      { q: 'Kan ik een vaste rit afspreken?', a: 'Ja, bijvoorbeeld voor dagbesteding.' },
    ],
    en: {
      metaDescription: 'Rolstoeltaxi Zaandam: wheelchair transport in Zaanstad, to the Zaanse Schans, Amsterdam and Schiphol. Electric ramp, 24/7 emergency service. Call now.',
      lead: 'Zaandam is the main town of Zaanstad, on the Zaan river, with well-known sights and plenty of business activity. For a wheelchair ride that means: many rides to care, work and outings.',
      intro: [
        'Zaanstad is a collection of old Zaan villages by the water, with Zaandam as its largest town. The Zaanse Schans attracts many visitors, and the Zaans Museum and the Czaar Peterhuisje show why the region is famous.',
        "For residents in a wheelchair, it's less of a museum and more of an everyday town: to the GP, day care or family. We drive you there, and to Amsterdam and Schiphol too.",
      ],
      plekken: [
        { t: 'Zaanse Schans', d: 'The famous windmills and wooden houses. We drop you off at an accessible entrance.' },
        { t: 'Zaandam station', d: 'Connects to the train towards Amsterdam. We arrange the last stretch.' },
        { t: 'Gedempte Gracht and the centre', d: 'Shops and restaurants in the heart of Zaandam. We agree on a drop-off spot.' },
        { t: 'Zaans Museum and Czaar Peterhuisje', d: 'Two cultural spots nearby. We arrange the outbound and return trip.' },
        { t: 'Inntel Hotels Amsterdam-Zaandam', d: 'The eye-catching hotel on the Zaan. For overnight stays and events we pick you up.' },
        { t: 'Neighbourhoods in Zaanstad', d: 'We also serve Zaandijk, Koog aan de Zaan and Krommenie.' },
      ],
      ritten: [
        { t: 'Zaandam to Amsterdam', d: 'For appointments, family visits or a day in the city.' },
        { t: 'Zaandam to Schiphol', d: 'For flights from Schiphol, with luggage.' },
        { t: 'Zaandam to Purmerend', d: 'To the other side of the region.' },
        { t: 'Zaandam to Haarlem', d: 'For care or family in Haarlem.' },
        { t: 'Within Zaanstad', d: 'From home to day care or the GP.' },
      ],
      spoed: "In Zaandam, an emergency ride can be needed for a discharge or an unexpected appointment. Call the emergency line with your address and destination, and we'll give you the arrival time and price.",
      bereik: 'Zaandam has a lot of water and bridges. Our drivers know the routes and choose the right way through. For an address on a narrow road, we agree on a pickup point beforehand.',
      faqs: [
        { q: 'Can you take me to the Zaanse Schans?', a: 'Yes, we drop you off at an accessible entrance and agree on a pickup time.' },
        { q: 'Do you also drive in Zaandijk and Koog aan de Zaan?', a: 'Yes, all towns in Zaanstad.' },
        { q: 'Can I be taken to Schiphol?', a: "Yes, let us know your flight details, and we'll calculate backwards from the check-in deadline." },
        { q: 'Can I arrange a regular ride?', a: 'Yes, for example for day care.' },
      ],
    },
  },

  {
    slug: 'purmerend',
    name: 'Purmerend',
    region: 'Kennemerland en Noord-Holland',
    nearby: ['zaandam', 'amsterdam', 'alkmaar', 'beverwijk', 'diemen'],
    photo: { src: 'rolstoelbus-laadklep-hoogbouw.jpg', alt: 'Rolstoelbus met uitgeklapte laadklep', pos: 'center' },
    metaDescription: 'Rolstoeltaxi Purmerend: rolstoelvervoer in Purmerend en Waterland, naar Amsterdam, Zaandam en Schiphol. Elektrische laadklep, 24/7 spoedservice. Bel direct.',
    lead: 'Purmerend ligt in Waterland, een polderlandschap met dijken, sloten en veel ruimte. Openbaar vervoer is er goed, maar niet altijd praktisch als u een rolstoel heeft.',
    intro: [
      'Purmerend is een van de grootste plaatsen in de regio, met een centrum aan de Koemarkt en grote woonwijken zoals Weidevenne. Daaromheen liggen de polders, waar de wegen smal zijn en de afstanden groot.',
      'Wij halen u op in Purmerend en de omliggende dorpen, en brengen u naar Amsterdam, Zaandam of Schiphol. Voor spoed belt u direct, voor vaste ritten plannen we een schema.',
    ],
    plekken: [
      { t: 'Koemarkt en het centrum', d: 'Winkels, horeca en het stadhuis. We spreken een toegankelijke afzetplek af.' },
      { t: 'Busstation Purmerend', d: 'Het knooppunt voor de bus richting Amsterdam en Zaandam. Wij regelen de rit als de bus niet lukt.' },
      { t: 'Weidevenne', d: 'Een grote nieuwbouwwijk met veel appartementen. De chauffeur helpt tot in de lift.' },
      { t: 'De Beemster', d: 'Het UNESCO-polderlandschap ten noorden van Purmerend, voor een dagje uit.' },
      { t: 'Overwhere en Gors', d: 'Twee wijken aan de oostkant, waar we regelmatig ophalen.' },
      { t: 'Waterlandse dorpen', d: 'Ook Broek in Waterland en Monnickendam vallen in ons werkgebied.' },
    ],
    ritten: [
      { t: 'Purmerend naar Amsterdam', d: 'Voor afspraken, zorg of familiebezoek.' },
      { t: 'Purmerend naar Zaandam', d: 'Van oost naar west, door Waterland.' },
      { t: 'Purmerend naar Schiphol', d: 'Rechtstreeks naar de luchthaven.' },
      { t: 'Purmerend naar Alkmaar', d: 'Naar het noorden, voor familie of zorg.' },
      { t: 'Binnen Purmerend', d: 'Van huis naar dagbesteding of de huisarts.' },
    ],
    spoed: 'In Purmerend kan spoed nodig zijn bij een ontslag of onverwachte afspraak. Bel de spoedlijn met uw adres en bestemming, dan noemen we de aankomsttijd en de prijs.',
    bereik: 'In Purmerend zelf zijn de wegen breed. In de polders zijn ze smal en soms ongeschikt voor een grote bus; dan spreken we vooraf een ophaalpunt af.',
    faqs: [
      { q: 'Rijden jullie ook in Waterland?', a: 'Ja, ook in Broek in Waterland, Monnickendam en de omliggende dorpen.' },
      { q: 'Kunnen jullie mij naar Amsterdam brengen?', a: 'Ja, dat is een veelgevraagde rit voor afspraken en familiebezoek.' },
      { q: 'Is een vaste rit mogelijk?', a: 'Ja, bijvoorbeeld voor dagbesteding of een terugkerende behandeling.' },
      { q: 'Werken jullie ook in het weekend?', a: 'Ja, we zijn 24/7 bereikbaar.' },
    ],
    en: {
      metaDescription: 'Rolstoeltaxi Purmerend: wheelchair transport in Purmerend and Waterland, to Amsterdam, Zaandam and Schiphol. Electric ramp, 24/7 emergency service. Call now.',
      lead: 'Purmerend lies in Waterland, a polder landscape with dikes, ditches and plenty of space. Public transport is good there, but not always practical if you use a wheelchair.',
      intro: [
        'Purmerend is one of the largest towns in the region, with a centre on the Koemarkt and large residential areas such as Weidevenne. Around it lie the polders, where the roads are narrow and the distances large.',
        'We pick you up in Purmerend and the surrounding villages, and take you to Amsterdam, Zaandam or Schiphol. For an emergency you call directly, for regular rides we schedule a plan.',
      ],
      plekken: [
        { t: 'Koemarkt and the centre', d: 'Shops, restaurants and the town hall. We agree on an accessible drop-off spot.' },
        { t: 'Purmerend bus station', d: "The hub for the bus towards Amsterdam and Zaandam. We arrange the ride when the bus isn't an option." },
        { t: 'Weidevenne', d: 'A large new-build neighbourhood with many apartments. The driver helps as far as the lift.' },
        { t: 'De Beemster', d: 'The UNESCO polder landscape north of Purmerend, for a day out.' },
        { t: 'Overwhere and Gors', d: 'Two neighbourhoods on the east side, where we regularly pick up.' },
        { t: 'Waterland villages', d: 'Broek in Waterland and Monnickendam are within our service area too.' },
      ],
      ritten: [
        { t: 'Purmerend to Amsterdam', d: 'For appointments, care or family visits.' },
        { t: 'Purmerend to Zaandam', d: 'From east to west, through Waterland.' },
        { t: 'Purmerend to Schiphol', d: 'Straight to the airport.' },
        { t: 'Purmerend to Alkmaar', d: 'To the north, for family or care.' },
        { t: 'Within Purmerend', d: 'From home to day care or the GP.' },
      ],
      spoed: "In Purmerend, an emergency ride can be needed for a discharge or unexpected appointment. Call the emergency line with your address and destination, and we'll give you the arrival time and price.",
      bereik: 'In Purmerend itself the roads are wide. In the polders they are narrow and sometimes unsuitable for a large vehicle; in that case we agree on a pickup point beforehand.',
      faqs: [
        { q: 'Do you also drive in Waterland?', a: 'Yes, in Broek in Waterland, Monnickendam and the surrounding villages too.' },
        { q: 'Can you take me to Amsterdam?', a: 'Yes, that is a frequently requested ride for appointments and family visits.' },
        { q: 'Is a regular ride possible?', a: 'Yes, for example for day care or a recurring treatment.' },
        { q: 'Do you also work on weekends?', a: 'Yes, we are reachable 24/7.' },
      ],
    },
  },

  {
    slug: 'alkmaar',
    name: 'Alkmaar',
    region: 'Kennemerland en Noord-Holland',
    nearby: ['beverwijk', 'purmerend', 'zaandam', 'haarlem', 'amsterdam'],
    photo: { src: 'scootmobiel-laadklep.jpg', alt: 'Scootmobiel op de laadklep van de rolstoelbus voor een gebouw', pos: 'center' },
    metaDescription: 'Rolstoeltaxi Alkmaar: rolstoelvervoer naar de kaasmarkt, het centrum en de zorg, vanuit Noord-Holland. Elektrische laadklep, 24/7 spoedservice. Bel direct.',
    lead: 'Alkmaar is de stad van de kaasmarkt, de grachten en het Waagplein. Voor een rolstoelrit betekent dat: veel toerisme op vaste momenten, en een rustige stad daarbuiten.',
    intro: [
      'De kaasmarkt trekt in het seizoen op vrijdagochtend veel bezoekers naar het Waagplein. Voor iemand in een rolstoel is dat een prachtig gezicht, maar ook een drukke plek om te bereiken. Wij spreken vooraf af waar u wordt afgezet en op welk tijdstip we u weer ophalen.',
      'Daarbuiten is Alkmaar een rustige stad met een historisch centrum, grachten en een station. Wij rijden u van en naar afspraken, zorg of familie, in Alkmaar en de omgeving.',
    ],
    plekken: [
      { t: 'Waagplein en de kaasmarkt', d: 'Het bekendste plein van Alkmaar. Op marktdagen plannen we vooraf een afzetplek.' },
      { t: 'Grote of Sint-Laurenskerk', d: 'Het grote monument in het centrum. We zetten u af bij de toegankelijke ingang.' },
      { t: 'Station Alkmaar', d: 'Aansluiting op de trein. Wij regelen het laatste stuk.' },
      { t: 'Verdronkenoord en de grachten', d: 'Rustige straten langs het water, voor een wandeling of dagje uit.' },
      { t: 'Victoriepark en Alkmaarderhout', d: 'Groene plekken vlak bij het centrum.' },
      { t: 'Wijken en zorgcomplexen', d: 'We halen u op bij de deur, en helpen over drempels.' },
    ],
    ritten: [
      { t: 'Alkmaar naar Amsterdam', d: 'Voor afspraken, familiebezoek of een dagje stad.' },
      { t: 'Alkmaar naar Schiphol', d: 'Voor vluchten, met bagage.' },
      { t: 'Alkmaar naar Haarlem', d: 'Naar het zuiden, voor zorg of familie.' },
      { t: 'Alkmaar naar Purmerend', d: 'Door Noord-Holland, naar de andere kant van de regio.' },
      { t: 'Binnen Alkmaar', d: 'Van huis naar dagbesteding of de huisarts.' },
    ],
    spoed: 'In Alkmaar kan spoed nodig zijn bij een ontslag of een onverwachte afspraak. Bel de spoedlijn met uw adres en bestemming, dan noemen we de aankomsttijd en de prijs.',
    bereik: 'Het centrum van Alkmaar is deels autoluw en heeft grachten. Wij spreken vooraf af waar u wordt opgehaald. Buiten het centrum is het eenvoudiger: daar rijdt de bus doorgaans tot voor de deur.',
    faqs: [
      { q: 'Kunnen jullie mij naar de kaasmarkt brengen?', a: 'Ja, heen en terug. Op marktdagen spreken we vooraf een afzetplek en ophaaltijd af.' },
      { q: 'Kan ik een scootmobiel meenemen?', a: 'Ja, de laadklep is geschikt voor scootmobielen. Geef het model door bij het boeken.' },
      { q: 'Kunnen jullie mij naar Schiphol brengen?', a: 'Ja, geef uw vluchtgegevens door, dan rekenen we terug vanaf de incheckdeadline.' },
      { q: 'Kan ik een vaste rit afspreken?', a: 'Ja, bijvoorbeeld voor dagbesteding of een terugkerende behandeling.' },
    ],
    en: {
      metaDescription: 'Rolstoeltaxi Alkmaar: wheelchair transport to the cheese market, the centre and care facilities, from throughout North Holland. Electric ramp, 24/7 emergency service. Call now.',
      lead: 'Alkmaar is the town of the cheese market, the canals and the Waagplein. For a wheelchair ride that means: lots of tourism at set times, and a quiet town outside of that.',
      intro: [
        "During the season, the cheese market draws many visitors to the Waagplein on Friday mornings. For someone in a wheelchair, it's a beautiful sight, but also a busy spot to reach. We agree beforehand where you'll be dropped off and what time we'll pick you up again.",
        'Outside of that, Alkmaar is a quiet town with a historic centre, canals and a station. We drive you to and from appointments, care or family, in Alkmaar and the surrounding area.',
      ],
      plekken: [
        { t: 'Waagplein and the cheese market', d: 'The most famous square in Alkmaar. On market days we plan a drop-off spot in advance.' },
        { t: 'Grote of Sint-Laurenskerk', d: 'The large monument in the centre. We drop you off at the accessible entrance.' },
        { t: 'Alkmaar station', d: 'Connects to the train. We arrange the last stretch.' },
        { t: 'Verdronkenoord and the canals', d: 'Quiet streets along the water, for a walk or a day out.' },
        { t: 'Victoriepark and Alkmaarderhout', d: 'Green spots close to the centre.' },
        { t: 'Neighbourhoods and care complexes', d: 'We pick you up at the door, and help over thresholds.' },
      ],
      ritten: [
        { t: 'Alkmaar to Amsterdam', d: 'For appointments, family visits or a day in the city.' },
        { t: 'Alkmaar to Schiphol', d: 'For flights, with luggage.' },
        { t: 'Alkmaar to Haarlem', d: 'To the south, for care or family.' },
        { t: 'Alkmaar to Purmerend', d: 'Through North Holland, to the other side of the region.' },
        { t: 'Within Alkmaar', d: 'From home to day care or the GP.' },
      ],
      spoed: "In Alkmaar, an emergency ride can be needed for a discharge or an unexpected appointment. Call the emergency line with your address and destination, and we'll give you the arrival time and price.",
      bereik: "Alkmaar's centre is partly car-free and has canals. We agree beforehand where you'll be picked up. Outside the centre it's easier: the vehicle usually drives right up to the door.",
      faqs: [
        { q: 'Can you take me to the cheese market?', a: 'Yes, both ways. On market days we agree on a drop-off spot and pickup time beforehand.' },
        { q: 'Can I bring a mobility scooter?', a: 'Yes, the ramp is suitable for mobility scooters. Let us know the model when booking.' },
        { q: 'Can you take me to Schiphol?', a: "Yes, let us know your flight details, and we'll calculate backwards from the check-in deadline." },
        { q: 'Can I arrange a regular ride?', a: 'Yes, for example for day care or a recurring treatment.' },
      ],
    },
  },
];
